DeviceLibrary::CPelicano
CcmdMotors
Ouve la trappe de rejet, fait tourner le moteur et referme la trappe de rejet.
OptionFlag
Limitation de l'acceptation non implémentée
Header
Lecture des optocoupleurs à la sortie des pièces.
CoinPresent
Pas de pièce dans le container.
bool DeviceLibrary.CPelicano.isPelicanoInitialized
Etat DeviceLibrary.CPelicano.nextState
Contient le prochaine etat.
Referenced by DeviceLibrary.CPelicano.Task.
CoinPresent DeviceLibrary.CPelicano.coinInContainer
Referenced by DeviceLibrary.CPelicano.CPelicano.
bool DeviceLibrary.CPelicano.IsPelicanoInitialized
Indique si le Pelicano est initialisé.
Referenced by DeviceLibrary.CPelicano.CPelicano.
CoinPresent DeviceLibrary.CPelicano.CoinInContainer
Contient l'indicateur de présence de pièce dans le container.
Referenced by DeviceLibrary.CPelicano.CPelicano.
override byte DeviceLibrary.CPelicano.OptoStates
Verification des opto-coupleurs
Header 236
Referenced by DeviceLibrary.CPelicano.Task.
bool DeviceLibrary.CPelicano.IsCoinPresent
Vérifie si une pièce est présente dans le cointainer.
true si au moins une pièce est présente dans le bol false s'il n'y a pas de pièce
Referenced by DeviceLibrary.CPelicano.Task.
OptionFlag DeviceLibrary.CPelicano.AcceptLimitFeature
Retourne le traitement d'une limite d'acceptation.
UNSUPPORTED si l'option de limit d'acceptation est désactivée. SUPPORTED si l'option de limit d'acceptation est activée.
Referenced by DeviceLibrary.CPelicano.Task.
override int DeviceLibrary.CPelicano.SerialNumber
Lecture du numéro de série du Pelicano
Le numéro de série
byte DeviceLibrary.CPelicano.SpeedMotor
Renvoie la vitesse du moteur.
La vitesse du moteur en pourcentage. 0 si la command ne renvoit rien.
Referenced by DeviceLibrary.CPelicano.Task.
byte DeviceLibrary.CPelicano.PocketTime
Renvoie le pocket time
Le délai entre 2 trous dans le disque * 4 ms. 0 si la fonction ne retourne pas la valeur
Referenced by DeviceLibrary.CPelicano.Task.
byte DeviceLibrary.CPelicano.ActivateMotor(CcmdMotors command, byte data=0)
Commande moteur du pelicano.
command Sous-command de la fonction. data vitesse en pourcentage. Donnée dépendant de la sous command.
References DeviceLibrary.messagesText.cmdMotorPelicano, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.messagesText.errMotorPelicano, DeviceLibrary.CccTalk.IsCmdccTalkSended.
Referenced by DeviceLibrary.CPelicano.CPRStart, DeviceLibrary.CPelicano.TrashCycle.
void DeviceLibrary.CPelicano.TrashCycle(CcmdMotors level=CcmdMotors.TRASH1)
Active le moteur en mode trash.
References DeviceLibrary.CPelicano.ActivateMotor, DeviceLibrary.messagesText.cmdMotorPelicanoInProgress, DeviceLibrary.messagesText.cmdMotorPelicanoMode, DeviceLibrary.messagesText.erreur.
Referenced by DeviceLibrary.CPelicano.CPelicano, DeviceLibrary.CPelicano.Task.
void DeviceLibrary.CPelicano.CPRStart()
Active le moteur en mode CPR.
References DeviceLibrary.CPelicano.ActivateMotor, DeviceLibrary.messagesText.cmdMotorPelicanoInProgress, DeviceLibrary.messagesText.cmdMotorPelicanoMode, DeviceLibrary.messagesText.erreur, DeviceLibrary.messagesText.errMotorPelicano.
override void DeviceLibrary.CPelicano.Task()
Tâche de la machine d'état du Pelicano
References DeviceLibrary.CPelicano.AcceptLimitFeature, DeviceLibrary.CCoinValidator.BackEventCounter, DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CCoinValidator.creditBuffer, DeviceLibrary.messagesText.erreur, DeviceLibrary.CCoinValidator.CCVcreditBuffer.EventCounter, DeviceLibrary.CCoinValidator.ExitSensor, DeviceLibrary.CPelicano.IsCoinPresent, DeviceLibrary.CCoinValidator.IsCVInitialized, DeviceLibrary.CcashReader.MasterInhibitStatus, DeviceLibrary.CPelicano.nextState, DeviceLibrary.CPelicano.OptoStates, DeviceLibrary.CPelicano.PocketTime, DeviceLibrary.CcashReader.PollingDelay, DeviceLibrary.CPelicano.SpeedMotor, DeviceLibrary.CCoinValidator.State, DeviceLibrary.CDevicesManager.ToPay, DeviceLibrary.CPelicano.TrashCycle, DeviceLibrary.CCoinValidator.TrashLid.
DeviceLibrary.CPelicano.CPelicano()
Constructeur
References DeviceLibrary.CPelicano.coinInContainer, DeviceLibrary.CPelicano.CoinInContainer, DeviceLibrary.CCoinValidator.ExitSensor, DeviceLibrary.CPelicano.IsPelicanoInitialized, DeviceLibrary.CPelicano.TrashCycle, DeviceLibrary.CCoinValidator.TrashLid.