DeviceLibrary::CCoinValidator::CCVcreditBuffer
readonly CCoinValidator DeviceLibrary.CCoinValidator.CCVcreditBuffer.owner
Instance de la classe proprietaire du buffer.
Referenced by DeviceLibrary.CCoinValidator.CCVcreditBuffer.CCVcreditBuffer, DeviceLibrary.CCoinValidator.CCVcreditBuffer.GetBufferCredit.
byte DeviceLibrary.CCoinValidator.CCVcreditBuffer.eventCounter
byte [,] DeviceLibrary.CCoinValidator.CCVcreditBuffer.result
Referenced by DeviceLibrary.CCoinValidator.CCVcreditBuffer.GetResult, DeviceLibrary.CCoinValidator.CCVcreditBuffer.SetResult.
byte DeviceLibrary.CCoinValidator.CCVcreditBuffer.EventCounter
Compteur d'évenements crédits ou erreurs
Referenced by DeviceLibrary.CCoinValidator.CCVcreditBuffer.CCVcreditBuffer, DeviceLibrary.CCoinValidator.CheckCreditBuffer, DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CCoinValidator.CCVcreditBuffer.GetBufferCredit, DeviceLibrary.CPelicano.Task.
DeviceLibrary.CCoinValidator.CCVcreditBuffer.CCVcreditBuffer(CCoinValidator owner)
Contructeur
References DeviceLibrary.CCoinValidator.CCVcreditBuffer.EventCounter, DeviceLibrary.CCoinValidator.CCVcreditBuffer.owner, DeviceLibrary.CCoinValidator.CCVcreditBuffer.SetResult.
void DeviceLibrary.CCoinValidator.CCVcreditBuffer.GetBufferCredit()
Lit le buffer de credit ou de code erreur.
Header 229
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CCoinValidator.CCVcreditBuffer.EventCounter, DeviceLibrary.CCoinValidator.CCVcreditBuffer.GetResult, DeviceLibrary.CccTalk.IsCmdccTalkSended, DeviceLibrary.CCoinValidator.CCVcreditBuffer.owner.
byte [,] DeviceLibrary.CCoinValidator.CCVcreditBuffer.GetResult()
Buffer contenant les informations sur les évenements.
References DeviceLibrary.CCoinValidator.CCVcreditBuffer.result.
Referenced by DeviceLibrary.CCoinValidator.CheckCreditBuffer, DeviceLibrary.CCoinValidator.CCVcreditBuffer.GetBufferCredit.
void DeviceLibrary.CCoinValidator.CCVcreditBuffer.SetResult(byte[,] value)
Buffer contenant les informations sur les évenements.
References DeviceLibrary.CCoinValidator.CCVcreditBuffer.result.
Referenced by DeviceLibrary.CCoinValidator.CCVcreditBuffer.CCVcreditBuffer.