DeviceLibrary::CCoinValidator
CVStatus
Monnayeur à l'état normal
LowerSensor
Senseurs de sortie sont libres.
TrashDoor
Trappe de sortie du Pelicano fermée.
Header
Cette commande demande le status du monnayeur.
CVErrorCodes
Pas d'erreur.
Etat
Etat pour l'initialisation du monnayeur.
byte DeviceLibrary.CCoinValidator.backEventCounter
Referenced by DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CCoinValidator.Init.
byte DeviceLibrary.CCoinValidator.channelInProgress
Referenced by DeviceLibrary.CCoinValidator.CheckState.
byte DeviceLibrary.CCoinValidator.defaultSorterPath
Chemin de tri par défaut.
Referenced by DeviceLibrary.CCoinValidator.Init.
CErroCV DeviceLibrary.CCoinValidator.errorCV
Instance de la classe des erreurs du monnayeurs.
Referenced by DeviceLibrary.CCoinValidator.CheckCreditBuffer, DeviceLibrary.CCoinValidator.Init.
LowerSensor DeviceLibrary.CCoinValidator.exitSensor
bool DeviceLibrary.CCoinValidator.isCVInitialized
bool DeviceLibrary.CCoinValidator.isCVToBeActivated
bool DeviceLibrary.CCoinValidator.isCVToBeDeactivated
Referenced by DeviceLibrary.CCoinValidator.CheckState.
byte DeviceLibrary.CCoinValidator.overrideMask
byte DeviceLibrary.CCoinValidator.sorterPath
Chemin utilisé dans le trieur pour le canal
Referenced by DeviceLibrary.CCoinValidator.CheckState.
Etat DeviceLibrary.CCoinValidator.state
TrashDoor DeviceLibrary.CCoinValidator.trashLid
CCVcreditBuffer DeviceLibrary.CCoinValidator.creditBuffer
Buffer contenant les informations sur les pièces lues ou les erreurs rencontrées
Referenced by DeviceLibrary.CCoinValidator.CheckCreditBuffer, DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CCoinValidator.Init, DeviceLibrary.CPelicano.Task.
const byte DeviceLibrary.CCoinValidator.numChannel
Nombre de canaux du monnayeur.
Referenced by DeviceLibrary.CcoinsCounters.CCoinInCB.CCoinInCB, DeviceLibrary.CcoinsCounters.CcoinsCounters, DeviceLibrary.CCoinValidator.Init.
CCanal [] DeviceLibrary.CCoinValidator.canaux
Tableau des canaux
Referenced by DeviceLibrary.CDevicesManager.BNRCashBoxRemoved, AtmbTestDevices.FormMain.ButtonCounters_Click, DeviceLibrary.CCoinValidator.CheckCreditBuffer, DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CCoinValidator.Init.
Thread DeviceLibrary.CCoinValidator.CVTask
Thread de gestion de la machine d'état du monnayeur.
Referenced by DeviceLibrary.CCoinValidator.CCoinValidator.
byte DeviceLibrary.CCoinValidator.ChannelInProgress
Numéro du canal en cours d'utilisation.
Referenced by DeviceLibrary.CCoinValidator.CheckState.
byte DeviceLibrary.CCoinValidator.DataBaseVersion
Renvoi la version de la data base.
Header 243
Referenced by DeviceLibrary.CCoinValidator.CheckState.
byte DeviceLibrary.CCoinValidator.DefaultSorterPath
Renvoi le chemin de tri par défaut.
Le chemin de tri par défaut. 0 en cas d'échec. Header 188
Referenced by DeviceLibrary.CCoinValidator.CheckState.
byte DeviceLibrary.CCoinValidator.OverrideMask
Masque des chemins optionnels
Referenced by DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CCoinValidator.Init.
byte DeviceLibrary.CCoinValidator.OverrideStatus
Renvoie l'override status.
L'octet de l'override Header 221
Referenced by DeviceLibrary.CCoinValidator.CheckState.
CVStatus DeviceLibrary.CCoinValidator.Status
Renvoi le status du coin validator
status
Referenced by DeviceLibrary.CCoinValidator.CheckState.
byte DeviceLibrary.CCoinValidator.BackEventCounter
Tableau contenant l'identification des pièces.
Sauvegarde du compteur d'événement.
Referenced by DeviceLibrary.CCoinValidator.CheckCreditBuffer, DeviceLibrary.CCoinValidator.Init, DeviceLibrary.CPelicano.Task.
LowerSensor DeviceLibrary.CCoinValidator.ExitSensor
Indique si les optiques de sortie sont libre.
Referenced by DeviceLibrary.CPelicano.CPelicano, DeviceLibrary.CPelicano.Task.
bool DeviceLibrary.CCoinValidator.IsCVInitialized
Flag indiquant si le monnayeur est initialisé.
Referenced by DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CCoinValidator.Init, DeviceLibrary.CPelicano.Task.
Etat DeviceLibrary.CCoinValidator.State
Etat de la machie d'état.
Referenced by DeviceLibrary.CCoinValidator.CCoinValidator, DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CPelicano.Task.
TrashDoor DeviceLibrary.CCoinValidator.TrashLid
Contient l'indicateur d'ouverture du containner.
Referenced by DeviceLibrary.CPelicano.CPelicano, DeviceLibrary.CPelicano.Task.
bool DeviceLibrary.CCoinValidator.IsCVToBeActivated
Indique si le monnayeur doit être adtivé.
Referenced by DeviceLibrary.CCoinValidator.CheckState.
bool DeviceLibrary.CCoinValidator.IsCVToBeDeactivated
Indique si le monnayeur doit être adtivé.
Referenced by DeviceLibrary.CCoinValidator.CheckState.
DeviceLibrary.CCoinValidator.CCoinValidator()
Constructeur de la class CCoinValidator
References DeviceLibrary.CCoinValidator.CVTask, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CccTalk.IsDeviceReseted, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CccTalk.SimplePoll, DeviceLibrary.CCoinValidator.State, DeviceLibrary.CCoinValidator.Task.
void DeviceLibrary.CCoinValidator.CheckState()
Traitement des états du monnayers.
References DeviceLibrary.CCoinValidator.backEventCounter, DeviceLibrary.CccTalk.BuildCode, DeviceLibrary.CCoinValidator.canaux, DeviceLibrary.CCoinValidator.channelInProgress, DeviceLibrary.CCoinValidator.ChannelInProgress, DeviceLibrary.CCoinValidator.CheckCreditBuffer, DeviceLibrary.CCoinValidator.creditBuffer, DeviceLibrary.CCoinValidator.DataBaseVersion, DeviceLibrary.CCoinValidator.DefaultSorterPath, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.CccTalk.EquipementCategory, DeviceLibrary.messagesText.erreur, DeviceLibrary.CCoinValidator.CCVcreditBuffer.EventCounter, DeviceLibrary.CcashReader.GetInhibitMask, DeviceLibrary.CCoinValidator.Init, DeviceLibrary.CCoinValidator.IsCVInitialized, DeviceLibrary.CCoinValidator.IsCVToBeActivated, DeviceLibrary.CCoinValidator.isCVToBeDeactivated, DeviceLibrary.CCoinValidator.IsCVToBeDeactivated, DeviceLibrary.CccTalk.IsDeviceReseted, DeviceLibrary.CccTalk.Manufacturer, DeviceLibrary.CcashReader.MasterDisable, DeviceLibrary.CcashReader.MasterEnable, DeviceLibrary.CcashReader.MasterInhibitStatus, DeviceLibrary.CCoinValidator.OverrideMask, DeviceLibrary.CCoinValidator.OverrideStatus, DeviceLibrary.CcashReader.PollingDelay, DeviceLibrary.CcashReader.PollingPriority, DeviceLibrary.CccTalk.ProductCode, DeviceLibrary.CcashReader.SelfTest, DeviceLibrary.CccTalk.SerialNumber, DeviceLibrary.CcashReader.SetInhibitStatus, DeviceLibrary.CCoinValidator.SetOverrideStatus, DeviceLibrary.CccTalk.SimplePoll, DeviceLibrary.CCoinValidator.sorterPath, DeviceLibrary.CCoinValidator.State, DeviceLibrary.CCoinValidator.Status, DeviceLibrary.CccTalk.SWRev, DeviceLibrary.CCoinValidator.TestSolenoid.
Referenced by DeviceLibrary.CPelicano.Task, DeviceLibrary.CCoinValidator.Task.
byte [] DeviceLibrary.CCoinValidator.GetVariablesSet()
Les donnees variables du monnaayeur.
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CccTalk.IsCmdccTalkSended.
override void DeviceLibrary.CCoinValidator.Init()
Initialisation du monnayeur.
References DeviceLibrary.CCoinValidator.backEventCounter, DeviceLibrary.CCoinValidator.BackEventCounter, DeviceLibrary.CCoinValidator.canaux, DeviceLibrary.CCoinValidator.creditBuffer, DeviceLibrary.CCoinValidator.defaultSorterPath, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.CDevicesManager.EnableChannelsCV, DeviceLibrary.CCoinValidator.errorCV, DeviceLibrary.CCoinValidator.IsCVInitialized, DeviceLibrary.CCoinValidator.numChannel, DeviceLibrary.CCoinValidator.OverrideMask, DeviceLibrary.CcashReader.PollingDelay, DeviceLibrary.CcashReader.SetInhibitMask.
Referenced by DeviceLibrary.CCoinValidator.CheckState.
override void DeviceLibrary.CCoinValidator.Task()
Tâche de la machine d'état du monnayeur.
References DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.CcashReader.PollingDelay.
Referenced by DeviceLibrary.CCoinValidator.CCoinValidator.
void DeviceLibrary.CCoinValidator.SetOverrideStatus(byte mask)
Modifie l'override status.
Header 222
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CccTalk.IsCmdccTalkSended.
Referenced by DeviceLibrary.CCoinValidator.CheckState.
bool DeviceLibrary.CCoinValidator.TestSolenoid(byte mask=0X01)
Active les activateurs du monnayeur
mask Masque correspondant aux bobines a activé.
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.messagesText.erreurCmd, DeviceLibrary.CccTalk.IsCmdccTalkSended, DeviceLibrary.messagesText.testSolenoid.
Referenced by DeviceLibrary.CCoinValidator.CheckState.
void DeviceLibrary.CCoinValidator.CheckCreditBuffer()
Cette fonction analyse le buffer des crédits et des codes erreurs
References DeviceLibrary.CCoinValidator.BackEventCounter, DeviceLibrary.CCoinValidator.canaux, DeviceLibrary.CcoinsCounters.coinsInAccepted, DeviceLibrary.CcoinsCounters.coinsInHopper, DeviceLibrary.CccTalk.counters, DeviceLibrary.CCoinValidator.creditBuffer, DeviceLibrary.CInserted.CVChannel, DeviceLibrary.CDevice.denominationInserted, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CCoinValidator.errorCV, DeviceLibrary.CCoinValidator.CCVcreditBuffer.EventCounter, DeviceLibrary.CDevice.eventListLock, DeviceLibrary.CCoinValidator.CCVcreditBuffer.GetResult, DeviceLibrary.CccTalk.ProductCode, DeviceLibrary.CcoinsCounters.totalAmountInCB, DeviceLibrary.CInserted.ValeurCent.
Referenced by DeviceLibrary.CCoinValidator.CheckState.