DeviceLibrary::CcashReader
InhibitStatus
Périphérique désactivé
Header
Délai recommandé pour vérifier le buffer de crédits et de code d'erreur
Au dela de ce délai le périphérique devrait être désactivé
readonly int [] DeviceLibrary.CcashReader.PriorityUnit
Tableau de conversion des unités dans la réponse au polling priority.
byte [] DeviceLibrary.CcashReader.inhibitMask
Referenced by DeviceLibrary.CcashReader.GetInhibitMask, DeviceLibrary.CcashReader.SetInhibitMask.
int DeviceLibrary.CcashReader.pollingDelay
InhibitStatus DeviceLibrary.CcashReader.MasterInhibitStatus
Renvoi l'activation du monnayeur
ENABLED si le monnayeur est activé DISABLED si le monnayeur est désactivé Header 227
Referenced by DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CPelicano.Task.
int DeviceLibrary.CcashReader.PollingDelay
Délai entre 2 interrogation du coin validator.
Referenced by DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CCoinValidator.Init, DeviceLibrary.CPelicano.Task, DeviceLibrary.CCoinValidator.Task.
int DeviceLibrary.CcashReader.PollingPriority
Renvoi le délai maximum du polling du périphérique.
Header 249Délai du polling ou 0 en cas d'échec de traitement
Referenced by DeviceLibrary.CCoinValidator.CheckState.
SelfTestResult DeviceLibrary.CcashReader.SelfTest
Effectue un test interne et renvoie le résultat.
Header 232
Referenced by DeviceLibrary.CCoinValidator.CheckState.
void DeviceLibrary.CcashReader.SetMasterInhibit(InhibitStatus status)
Active ou desactive le moyen de paiment
status = 1 pour activer , 0 pour désactiver Header 228 Les 7 bits de poids fort ne sont pas considérés.
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.messagesText.errMasterInhibitStatus, DeviceLibrary.CccTalk.IsCmdccTalkSended, DeviceLibrary.messagesText.sendMasterInhibitStatus.
Referenced by DeviceLibrary.CcashReader.MasterDisable, DeviceLibrary.CcashReader.MasterEnable.
byte [] DeviceLibrary.CcashReader.GetInhibitMask()
Masque d'ihnibition (2 octets pour 16 canaux)
References DeviceLibrary.CcashReader.inhibitMask.
Referenced by DeviceLibrary.CCoinValidator.CheckState.
void DeviceLibrary.CcashReader.GetInhibitMask(byte[] mask)
Retourne le mask d'inhibition des canaux
mask Buffer contenant les masks d'inhibitions
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.messagesText.getInhibitStatus, DeviceLibrary.CccTalk.IsCmdccTalkSended.
void DeviceLibrary.CcashReader.MasterDisable()
Desactive globalement le moyen de paiement
References DeviceLibrary.messagesText.deactivationCV, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CcashReader.SetMasterInhibit.
Referenced by DeviceLibrary.CCoinValidator.CheckState.
void DeviceLibrary.CcashReader.MasterEnable()
Activation globale du moyen de paiement
References DeviceLibrary.messagesText.activationCV, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CcashReader.SetMasterInhibit.
Referenced by DeviceLibrary.CCoinValidator.CheckState.
void DeviceLibrary.CcashReader.SetInhibitMask(byte[] value)
Masque d'ihnibition (2 octets pour 16 canaux)
References DeviceLibrary.CcashReader.inhibitMask.
Referenced by DeviceLibrary.CCoinValidator.Init.
void DeviceLibrary.CcashReader.SetInhibitStatus(byte[] mask)
Active ou desactive les canaux du monnayeur
mask masque d'inhibiton Header 231
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.messagesText.errInhibitStatus, DeviceLibrary.messagesText.inhibitStatus, DeviceLibrary.CccTalk.IsCmdccTalkSended.
Referenced by DeviceLibrary.CCoinValidator.CheckState.
override void DeviceLibrary.CcashReader.Task()
Tâche vérifiant les activitées du monnayeur