DeviceLibrary::CHopper
HopperError
Aucune erreur ou erreur non identifiée.
Etat
Initialisation du hopper
Header
Cette commande demande l'état des sondes de niveau du hopper
RegistrePos
Pas d'erreur. /summary>
LevelMask
Mask indiquant si le niveau base est atteint.
const byte DeviceLibrary.CHopper.maxHopper
Nombre maximum de hoppers
Referenced by DeviceLibrary.CcoinsCounters.CcoinsCounters.
CHopperError DeviceLibrary.CHopper.errorHopper
Instance de la class CerrorHopper
Referenced by DeviceLibrary.CHopper.AddErrorHopperEvent, DeviceLibrary.CHopper.Init, DeviceLibrary.CHopper.Task.
string DeviceLibrary.CHopper.name
Chaine d'identification du hopper.
Referenced by DeviceLibrary.CHopper.AddErrorHopperEvent, AtmbTestDevices.FormMain.ButtonHoppers_Click, DeviceLibrary.CHopper.CheckLevel, DeviceLibrary.CHopper.Empty, DeviceLibrary.CHopper.EventLevelHopper, DeviceLibrary.CHopper.ToString.
bool DeviceLibrary.CHopper.isEmptyingInProgress
Flag indiquant qu'un vidage est en cours.
Referenced by DeviceLibrary.CHopper.Empty, DeviceLibrary.CHopper.Init, DeviceLibrary.CHopper.Task.
const byte DeviceLibrary.CHopper.AddressBaseHoper
Adresse de base des hoppers.
Les numéros des hoppers commencent à 1 et la première adresse est 3 donc l'adresse d'un hopper s'obtient par : Numéro du Hopper + (première adresse(3) - 1) : (Adresse de base : 2)
Referenced by DeviceLibrary.CHopper.CHopper, DeviceLibrary.CHopper.CHopperVariableSet.GetVariableSet, DeviceLibrary.CHopper.Init.
CHopperVariableSet DeviceLibrary.CHopper.variables
Objet contenant l'ensemble des variables du hopper
Referenced by DeviceLibrary.CHopper.Init.
CHopperStatus DeviceLibrary.CHopper.dispenseStatus
Objet contenant le status de la distribution en cours.
Referenced by DeviceLibrary.CHopper.Init, DeviceLibrary.CHopper.Task.
byte DeviceLibrary.CHopper.Number
Numéro d'ordre du hopper
Referenced by DeviceLibrary.CHopper.CHopper, DeviceLibrary.CHopper.DispenseCoins, DeviceLibrary.CHopper.GetResetableCounter, DeviceLibrary.CHopper.Init.
CMemoryStorage DeviceLibrary.CHopper.memoryStorage
Informations sur le maintien des donneés en mémoires
Referenced by DeviceLibrary.CHopper.Init.
CEmptyCount DeviceLibrary.CHopper.emptyCount
Compteur de vidage;
Referenced by DeviceLibrary.CHopper.Empty, DeviceLibrary.CHopper.Init.
Thread DeviceLibrary.CHopper.HTask
Thread de la machine d'état du hopper.
Referenced by DeviceLibrary.CHopper.CHopper.
CLevel DeviceLibrary.CHopper.deviceLevel
Niveaux des périphériques.
Referenced by DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CHopper.CheckLevel, DeviceLibrary.CHopper.Dispense, DeviceLibrary.CHopper.Init.
const int DeviceLibrary.CHopper.pollDelayHopper
Delai en ms entre chaque pollinng du hopper
Referenced by DeviceLibrary.CHopper.Task.
const int DeviceLibrary.CHopper.polllDelayLevel
Delai en secondes entre 2 vérication de niveau
Referenced by DeviceLibrary.CHopper.Task.
CHopperCoinId DeviceLibrary.CHopper.hopperCoinID
Objet contenant l'identification des pièces contenus.
Referenced by DeviceLibrary.CHopper.Init.
bool DeviceLibrary.CHopper.isInitialized
Referenced by DeviceLibrary.CHopper.Task.
bool DeviceLibrary.CHopper.isOnError
Boolean indiquant que le hopper est operationel.
Referenced by DeviceLibrary.CHopper.Empty, DeviceLibrary.CHopper.SubCounters, DeviceLibrary.CHopper.Task.
uint DeviceLibrary.CHopper.coinValue
Referenced by DeviceLibrary.CHopper.SubCounters.
Etat DeviceLibrary.CHopper.state
Referenced by DeviceLibrary.CHopper.CHopper, DeviceLibrary.CHopper.Task.
byte [] DeviceLibrary.CHopper.cipherKey
Clé de chiffrement pour la distribution
Referenced by DeviceLibrary.CHopper.DispenseCoins, DeviceLibrary.CHopper.GetCipherKey, DeviceLibrary.CHopper.Init.
bool DeviceLibrary.CHopper.isMaxCurrentExceeded
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isTOOccured
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isMotorReversed
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isOptoPathBlocked
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isShortCircuit
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isOptoPermanentlyBlocked
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isPowerUpDetected
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isPayoutDisabled
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isOptoShorCircuit
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isSingleCoinMode
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isCheckSumAError
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isCheckSumBError
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isCheckSumCError
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isCheckSumDError
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isPowerFailMemoryWrite
Referenced by DeviceLibrary.CHopper.TestHopper.
bool DeviceLibrary.CHopper.isPINEnabled
Referenced by DeviceLibrary.CHopper.TestHopper.
byte DeviceLibrary.CHopper.coinsToDistribute
Referenced by DeviceLibrary.CHopper.Task.
uint DeviceLibrary.CHopper.levelFullSoft
uint DeviceLibrary.CHopper.levelHISoft
uint DeviceLibrary.CHopper.levelLOSoft
uint DeviceLibrary.CHopper.levelEmptySoft
uint DeviceLibrary.CHopper.defaultFilling
bool DeviceLibrary.CHopper.isDispensed
Referenced by DeviceLibrary.CHopper.Task.
bool DeviceLibrary.CHopper.isCritical
bool DeviceLibrary.CHopper.IsInitialized
Indique si le Hopper est initialisé.
Referenced by DeviceLibrary.CHopper.CHopper, DeviceLibrary.CHopper.Task.
uint DeviceLibrary.CHopper.CoinValue
Valeur de la pièce distribuée par le hopper.
Referenced by DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CHopper.Empty, DeviceLibrary.CHopper.CHopperStatus.GetHopperStatus, DeviceLibrary.CHopper.LoadHopper, DeviceLibrary.CHopper.SubCounters, DeviceLibrary.CHopper.Task.
long DeviceLibrary.CHopper.CoinsInHopper
Compteur du nombre de pièce dans le hopper
Referenced by DeviceLibrary.CHopper.CheckLevel, DeviceLibrary.CHopper.Empty, DeviceLibrary.CHopper.LoadHopper, DeviceLibrary.CHopper.SubCounters.
long DeviceLibrary.CHopper.AmountInHopper
Montant contenu dans le hopper.
Referenced by DeviceLibrary.CHopper.Empty, DeviceLibrary.CHopper.LoadHopper, DeviceLibrary.CHopper.SubCounters.
long DeviceLibrary.CHopper.CoinsOut
Compteur de pièces distribuées
Referenced by DeviceLibrary.CHopper.SubCounters.
long DeviceLibrary.CHopper.AmountOut
Montant distribués
Referenced by DeviceLibrary.CHopper.SubCounters.
long DeviceLibrary.CHopper.CoinsLoadedInHopper
Nombre de pièces chargées dans le hopper
Referenced by DeviceLibrary.CHopper.LoadHopper.
long DeviceLibrary.CHopper.AmountLoadedInHopper
Montant chargé dans le hopper.
Referenced by DeviceLibrary.CHopper.LoadHopper.
Etat DeviceLibrary.CHopper.State
Etat de la machine d'état des hoppers
Referenced by DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CHopper.Dispense, DeviceLibrary.CHopper.Empty, DeviceLibrary.CHopper.LoadHopper, DeviceLibrary.CHopper.Task.
bool DeviceLibrary.CHopper.IsMaxCurrentExceeded
Bolean indiquant qu'un dépassement du courant maximun a été atteint.
bool DeviceLibrary.CHopper.IsTOOccured
Bolean indiquant qu'un dépassement du temps alloué pour l'éjection d'une pièce est survenu.
Referenced by DeviceLibrary.CHopper.Empty, DeviceLibrary.CHopper.SubCounters.
bool DeviceLibrary.CHopper.IsMotorReversed
Bolean indiquant que suite à une surconsomation la rotation du moteur a été inversée pour corriger un bourrage.
bool DeviceLibrary.CHopper.IsOptoPathBlocked
Bolean indiquant que la sortie est bloquée.
bool DeviceLibrary.CHopper.IsShortCircuit
Bolean indiquant que la sortie est en court-circuit.
bool DeviceLibrary.CHopper.IsOptoPermanentlyBlocked
Bolean indiquant qu'un optocloupleur est bloqué en permanence.
bool DeviceLibrary.CHopper.IsPowerUpDetected
Bolean indiquant que le hopper est alimenté et un reset n'est pas encore effectué
bool DeviceLibrary.CHopper.IsPayoutDisabled
Bolean indiquant que le hopper n'est pas activé
bool DeviceLibrary.CHopper.IsOptoShorCircuit
Bolean indiquant qu'un optocoupleur est en court-circuit
bool DeviceLibrary.CHopper.IsSingleCoinMode
Bolean indiquant que le hopper est en mode pièce par pièce.
bool DeviceLibrary.CHopper.IsCheckSumAError
Bolean indiquant qu'une erreur de checksum dans le bloc de données A est survenue.
bool DeviceLibrary.CHopper.IsCheckSumBError
Bolean indiquant qu'une erreur de checksum dans le bloc de données B est survenue.
bool DeviceLibrary.CHopper.IsCheckSumCError
Bolean indiquant qu'une erreur de checksum dans le bloc de données B est survenue.
bool DeviceLibrary.CHopper.IsCheckSumDError
Bolean indiquant qu'une erreur de checksum dans le bloc de données D est survenue.
bool DeviceLibrary.CHopper.IsPowerFailMemoryWrite
Bolean indiquant qu'une chute de tension a eu lieu pendant une écriture mémoire.
bool DeviceLibrary.CHopper.IsPINEnabled
Bolean indiquant qu'un code pin est utilisé par le hopper
byte DeviceLibrary.CHopper.CoinsToDistribute
Nombre de pièce à distribuer
Referenced by DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CHopper.Dispense, DeviceLibrary.CHopper.Empty, DeviceLibrary.CHopper.Init, DeviceLibrary.CHopper.Task.
uint DeviceLibrary.CHopper.LevelFullSoft
Nombre maximum de pièces autorisées
Referenced by DeviceLibrary.CHopper.CheckLevel.
uint DeviceLibrary.CHopper.LevelHISoft
Nombre de pièce pour le niveau d'alerte haut
Referenced by DeviceLibrary.CHopper.CheckLevel.
uint DeviceLibrary.CHopper.LevelLOSoft
Nombre de pièce pour le niveau d'alerte bas
Referenced by DeviceLibrary.CHopper.CheckLevel.
uint DeviceLibrary.CHopper.LevelEmptySoft
Nombre minimum de pièces autorisées
Referenced by DeviceLibrary.CHopper.CheckLevel.
uint DeviceLibrary.CHopper.DefaultFilling
Nombre de pièces par défaut pour un remplissage.
bool DeviceLibrary.CHopper.IsDispensed
Boolean indiquant la fin d'une distribution
Referenced by DeviceLibrary.CHopper.Task.
bool DeviceLibrary.CHopper.IsCritical
Boolean indiquant si le hopper est indispensable au fonctionnement de la borne.
Referenced by DeviceLibrary.CHopper.CheckLevel.
byte DeviceLibrary.CHopper.LevelStatus
Renvoi les informations sur les niveaux des hoppers
Le masque des niveaux du hopper
bool DeviceLibrary.CHopper.IsHighLevelImplemented
Boolean indiquant si la détection du niveau haut est implémentée.
Referenced by DeviceLibrary.CHopper.Init.
bool DeviceLibrary.CHopper.IsLowLevelImplemented
Indique si la détection du niveau haut est implémentée.
Referenced by DeviceLibrary.CHopper.Init.
bool DeviceLibrary.CHopper.IsHighLevelReached
Boolean indiquant si le niveau hardware haut est atteint
Referenced by DeviceLibrary.CHopper.CheckLevel, DeviceLibrary.CHopper.Init.
bool DeviceLibrary.CHopper.IsLowLevelReached
Boolean indiquant si le niveau hardware bas est atteint
Referenced by DeviceLibrary.CHopper.CheckLevel, DeviceLibrary.CHopper.Init.
byte DeviceLibrary.CHopper.EmergecyStop
Nombre de byte restant à payer lorsque l'arrêt d'urgence du hopper est activé.
CHopperCoinId DeviceLibrary.CHopper.CoinId
Lecture des informations concernant la pièce gérée par le hopper
N'est pas pris en compte par la dll
Referenced by DeviceLibrary.CHopper.Init.
int DeviceLibrary.CHopper.delaypollLevel
Délai pour l'interrogation des niveaux lorsque le hopper est au repos.
Referenced by DeviceLibrary.CHopper.Task.
int DeviceLibrary.CHopper.GetResetableCounter()
Lit les informations du compteur interne du hopper
Nombre de pièces distribuées par le hopper
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CHopper.Number.
void DeviceLibrary.CHopper.PumpRNG()
Envoie un nombre aléatoire qui sera utilisé pour le chiffrement.
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CccTalk.IsCmdccTalkSended.
Referenced by DeviceLibrary.CHopper.Task.
bool DeviceLibrary.CHopper.DispenseCoins(byte number)
Commande demandant la distribution des pièces.
number Nombre de pièces à distribuer true si la commande a été envoyée et comprise En cas d'échec vérifier la procédure de validation précédent la commande.
References DeviceLibrary.CHopper.cipherKey, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CccTalk.IsCmdccTalkSended, DeviceLibrary.CHopper.Number.
Referenced by DeviceLibrary.CHopper.Task.
override void DeviceLibrary.CHopper.Init()
Initialisation du hopper
References DeviceLibrary.CHopper.AddressBaseHoper, DeviceLibrary.CHopper.cipherKey, DeviceLibrary.CHopper.CoinId, DeviceLibrary.CHopper.CoinsToDistribute, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.CHopper.deviceLevel, DeviceLibrary.CHopper.dispenseStatus, DeviceLibrary.CHopper.emptyCount, DeviceLibrary.CHopper.EnableHopper, DeviceLibrary.CccTalk.EquipementCategory, DeviceLibrary.messagesText.erreur, DeviceLibrary.CHopper.errorHopper, DeviceLibrary.CHopper.hopperCoinID, DeviceLibrary.CHopper.isEmptyingInProgress, DeviceLibrary.CHopper.IsHighLevelImplemented, DeviceLibrary.CHopper.IsHighLevelReached, DeviceLibrary.CHopper.IsLowLevelImplemented, DeviceLibrary.CHopper.IsLowLevelReached, DeviceLibrary.CHopper.memoryStorage, DeviceLibrary.CHopper.Number, DeviceLibrary.CccTalk.OptoStates, DeviceLibrary.CccTalk.SerialNumber, DeviceLibrary.CHopper.ToString, DeviceLibrary.CHopper.variables.
Referenced by DeviceLibrary.CHopper.Task.
void DeviceLibrary.CHopper.CheckLevel()
Véfication des niveaux du hopper.
References DeviceLibrary.CHopper.CoinsInHopper, DeviceLibrary.CHopper.deviceLevel, DeviceLibrary.messagesText.erreur, DeviceLibrary.CHopper.EventLevelHopper, DeviceLibrary.CHopper.CLevel.hardLevel, DeviceLibrary.CHopper.IsCritical, DeviceLibrary.CHopper.IsHighLevelReached, DeviceLibrary.CHopper.IsLowLevelReached, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CHopper.LevelEmptySoft, DeviceLibrary.CHopper.LevelFullSoft, DeviceLibrary.CHopper.LevelHISoft, DeviceLibrary.CHopper.LevelLOSoft, DeviceLibrary.CHopper.name, DeviceLibrary.CHopper.CLevel.softLevel.
Referenced by DeviceLibrary.CHopper.Task.
void DeviceLibrary.CHopper.Empty()
Demande le vidage du hopper;
References DeviceLibrary.CHopper.AmountInHopper, DeviceLibrary.CHopper.CoinsInHopper, DeviceLibrary.CHopper.CoinsToDistribute, DeviceLibrary.CHopper.CoinValue, DeviceLibrary.CccTalk.counters, DeviceLibrary.CccTalk.countersFile, DeviceLibrary.CHopper.emptyCount, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevice.eventListLock, DeviceLibrary.CHopper.isEmptyingInProgress, DeviceLibrary.CHopper.isOnError, DeviceLibrary.CHopper.IsTOOccured, DeviceLibrary.CHopper.name, DeviceLibrary.CHopper.State.
override string DeviceLibrary.CHopper.ToString()
Ìdentification du hopper.
Chaine de caractères identifiant le hopper.
References DeviceLibrary.CHopper.name.
Referenced by DeviceLibrary.CHopper.AddErrorHopperEvent, DeviceLibrary.CHopper.Init, DeviceLibrary.CHopper.Task.
void DeviceLibrary.CHopper.Dispense(byte coinsToDispense)
Provoque la distribution par le hopper en utilisant la machine d'état
coinsToDispense Nombre de token à distribuer
References DeviceLibrary.CHopper.CoinsToDistribute, DeviceLibrary.CHopper.deviceLevel, DeviceLibrary.CHopper.CLevel.hardLevel, DeviceLibrary.CHopper.CLevel.softLevel, DeviceLibrary.CHopper.State.
void DeviceLibrary.CHopper.SubCounters(long CoinsNumber)
Mise à jour des compteurs après une distribution.
CoinsNumber
References DeviceLibrary.CHopper.AmountInHopper, DeviceLibrary.CHopper.AmountOut, DeviceLibrary.CHopper.CoinsInHopper, DeviceLibrary.CHopper.CoinsOut, DeviceLibrary.CHopper.coinValue, DeviceLibrary.CHopper.CoinValue, DeviceLibrary.CHopper.isOnError, DeviceLibrary.CHopper.IsTOOccured.
Referenced by DeviceLibrary.CHopper.Task.
void DeviceLibrary.CHopper.LoadHopper(long CoinsNumber)
Recharge les compteurs du hopper
CoinsNumber
References DeviceLibrary.CHopper.AmountInHopper, DeviceLibrary.CHopper.AmountLoadedInHopper, DeviceLibrary.CHopper.CoinsInHopper, DeviceLibrary.CHopper.CoinsLoadedInHopper, DeviceLibrary.CHopper.CoinValue, DeviceLibrary.CHopper.State.
override void DeviceLibrary.CHopper.Task()
Tâche de la machine d'état du hopper.
References DeviceLibrary.CHopper.AddErrorHopperEvent, DeviceLibrary.CHopper.CheckLevel, DeviceLibrary.CHopper.CHopperError.Code, DeviceLibrary.CHopper.CHopperStatus.CoinsPaid, DeviceLibrary.CHopper.CHopperStatus.CoinsRemaining, DeviceLibrary.CHopper.coinsToDistribute, DeviceLibrary.CHopper.CoinsToDistribute, DeviceLibrary.CHopper.CoinValue, DeviceLibrary.CHopper.delaypollLevel, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.CHopper.DispenseCoins, DeviceLibrary.CHopper.dispenseStatus, DeviceLibrary.CHopper.EnableHopper, DeviceLibrary.messagesText.erreur, DeviceLibrary.CHopper.errorHopper, DeviceLibrary.CDevice.eventListLock, DeviceLibrary.CHopper.GetCipherKey, DeviceLibrary.CHopper.Init, DeviceLibrary.CccTalk.IsDeviceReseted, DeviceLibrary.CHopper.isDispensed, DeviceLibrary.CHopper.IsDispensed, DeviceLibrary.CHopper.isEmptyingInProgress, DeviceLibrary.CHopper.isInitialized, DeviceLibrary.CHopper.IsInitialized, DeviceLibrary.CHopper.isOnError, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CHopper.pollDelayHopper, DeviceLibrary.CHopper.polllDelayLevel, DeviceLibrary.CHopper.PumpRNG, DeviceLibrary.CHopper.state, DeviceLibrary.CHopper.State, DeviceLibrary.CHopper.SubCounters, DeviceLibrary.CHopper.TestHopper, DeviceLibrary.CHopper.ToString.
Referenced by DeviceLibrary.CHopper.CHopper.
DeviceLibrary.CHopper.CHopper(byte hopperNumber)
Constructeur
hopperNumber Numéro du hopper
References DeviceLibrary.CHopper.AddressBaseHoper, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CHopper.HTask, DeviceLibrary.CccTalk.IsDeviceReseted, DeviceLibrary.CHopper.IsInitialized, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CHopper.Number, DeviceLibrary.CccTalk.SimplePoll, DeviceLibrary.CHopper.state, DeviceLibrary.CHopper.Task.
void DeviceLibrary.CHopper.EnableHopper()
Autorise la distribution sur le hopper.
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CccTalk.IsCmdccTalkSended.
Referenced by DeviceLibrary.CHopper.Init, DeviceLibrary.CHopper.Task.
void DeviceLibrary.CHopper.GetCipherKey()
Récupère la clé qui sera utilisé pour le chiffrement de la distribution.
References DeviceLibrary.CHopper.cipherKey, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CccTalk.IsCmdccTalkSended.
Referenced by DeviceLibrary.CHopper.Task.
HopperError DeviceLibrary.CHopper.TestHopper()
Lecture des registres du hopper.
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CHopper.isCheckSumAError, DeviceLibrary.CHopper.isCheckSumBError, DeviceLibrary.CHopper.isCheckSumCError, DeviceLibrary.CHopper.isCheckSumDError, DeviceLibrary.CccTalk.IsCmdccTalkSended, DeviceLibrary.CHopper.isMaxCurrentExceeded, DeviceLibrary.CHopper.isMotorReversed, DeviceLibrary.CHopper.isOptoPathBlocked, DeviceLibrary.CHopper.isOptoPermanentlyBlocked, DeviceLibrary.CHopper.isOptoShorCircuit, DeviceLibrary.CHopper.isPayoutDisabled, DeviceLibrary.CHopper.isPINEnabled, DeviceLibrary.CHopper.isPowerFailMemoryWrite, DeviceLibrary.CHopper.isPowerUpDetected, DeviceLibrary.CHopper.isShortCircuit, DeviceLibrary.CHopper.isSingleCoinMode, DeviceLibrary.CHopper.isTOOccured.
Referenced by DeviceLibrary.CHopper.Task.
void DeviceLibrary.CHopper.EventLevelHopper(CEvent.Reason reason, object data)
Ajoute un évenement de niveau à liste des évenements.
reason Raison de l'évenement. data Donnée concernant l'évenement.
References DeviceLibrary.CDevice.eventListLock, DeviceLibrary.CHopper.name.
Referenced by DeviceLibrary.CHopper.CheckLevel.
void DeviceLibrary.CHopper.AddErrorHopperEvent()
Création d'un evénement.
References DeviceLibrary.CHopper.errorHopper, DeviceLibrary.CDevice.eventListLock, DeviceLibrary.CHopper.name, DeviceLibrary.CHopper.ToString.
Referenced by DeviceLibrary.CHopper.Task.