DeviceLibrary::CccTalk
Header
Commande d'ajustement ou de test interne.
SelfTestResult
OK
const byte DeviceLibrary.CccTalk.sizeOfBufferOut
Taille des buffers
Referenced by DeviceLibrary.CccTalk.IsCmdccTalkSended.
DefaultDevicesAddress DeviceLibrary.CccTalk.deviceAddress
object DeviceLibrary.CccTalk.verrou
Verrou du thread
Referenced by DeviceLibrary.CccTalk.IsCmdccTalkSended.
const string DeviceLibrary.CccTalk.fileCounterName
Nom du fichier contenant les compteurs.
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager.
CcoinsCounters DeviceLibrary.CccTalk.counters
Compteurs
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager, DeviceLibrary.CCoinValidator.CheckCreditBuffer, DeviceLibrary.CHopper.Empty, DeviceLibrary.CccTalk.ResetCounters.
BinaryFormatter DeviceLibrary.CccTalk.counterSerializer
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager, DeviceLibrary.CccTalk.ResetCounters.
Stream DeviceLibrary.CccTalk.countersFile
Fichier des compteurs.
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager, DeviceLibrary.CHopper.Empty, DeviceLibrary.CccTalk.ResetCounters, DeviceLibrary.CcoinsCounters.SaveCounters.
Mutex DeviceLibrary.CccTalk.mutexCCTalk
SerialPort DeviceLibrary.CccTalk.PortSerie
Port série utilisée par le bus ccTalk
Referenced by DeviceLibrary.CccTalk.CccTalk, DeviceLibrary.CDevicesManager.GetSerialPort, DeviceLibrary.CccTalk.IsCcTalkPort, DeviceLibrary.CccTalk.IsCmdccTalkSended.
string DeviceLibrary.CccTalk.BuildCode
Code de production du périphérique.
Referenced by DeviceLibrary.CCoinValidator.CheckState.
string DeviceLibrary.CccTalk.CommsRevision
Lecture de version ccTalk utilisée par le périphérique.
string DeviceLibrary.CccTalk.EquipementCategory
Code produit du périphérique.
Referenced by DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CHopper.Init.
string DeviceLibrary.CccTalk.SWRev
Retourne la révision software
Referenced by DeviceLibrary.CCoinValidator.CheckState.
DefaultDevicesAddress DeviceLibrary.CccTalk.DeviceAddress
Adresse du périphérique.
Referenced by DeviceLibrary.CPelicano.ActivateMotor, DeviceLibrary.CCoinValidator.CCoinValidator, DeviceLibrary.CCoinValidator.CheckCreditBuffer, DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CHopper.CHopper, DeviceLibrary.CHopper.DispenseCoins, DeviceLibrary.CHopper.EnableHopper, DeviceLibrary.CccTalk.GetASCII, DeviceLibrary.CCoinValidator.CCVcreditBuffer.GetBufferCredit, DeviceLibrary.CccTalk.GetByte, DeviceLibrary.CHopper.GetCipherKey, DeviceLibrary.CCoinValidator.CCanal.CCoindID.GetCoinId, DeviceLibrary.CMemoryStorage.GetDataBlock, DeviceLibrary.CMemoryStorage.GetDataStorageAvailability, DeviceLibrary.CHopper.CHopperStatus.GetHopperStatus, DeviceLibrary.CcashReader.GetInhibitMask, DeviceLibrary.CHopper.CHopperVariableSet.GetVariableSet, DeviceLibrary.CCoinValidator.GetVariablesSet, DeviceLibrary.CCoinValidator.Init, DeviceLibrary.CHopper.Init, DeviceLibrary.CccTalk.IsDeviceReseted, DeviceLibrary.CcashReader.MasterDisable, DeviceLibrary.CcashReader.MasterEnable, DeviceLibrary.CHopper.PumpRNG, DeviceLibrary.CMemoryStorage.SetDataBlock, DeviceLibrary.CcashReader.SetInhibitStatus, DeviceLibrary.CcashReader.SetMasterInhibit, DeviceLibrary.CCoinValidator.SetOverrideStatus, DeviceLibrary.CCoinValidator.CCanal.CSorter.SetSorterPath, DeviceLibrary.CHopper.CHopperVariableSet.SetVariable, DeviceLibrary.CCoinValidator.Task, DeviceLibrary.CHopper.Task, DeviceLibrary.CHopper.TestHopper, DeviceLibrary.CCoinValidator.TestSolenoid.
override string DeviceLibrary.CccTalk.Manufacturer
Retourne l'identifiant du fabricant.
Referenced by DeviceLibrary.CCoinValidator.CheckState.
virtual byte DeviceLibrary.CccTalk.OptoStates
Lecture de l'etat des otpocoupleurs du périphériques.
Referenced by DeviceLibrary.CHopper.Init.
override string DeviceLibrary.CccTalk.ProductCode
Code produit du périphérique.
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager, DeviceLibrary.CCoinValidator.CheckCreditBuffer, DeviceLibrary.CCoinValidator.CheckState.
override int DeviceLibrary.CccTalk.SerialNumber
Retourne le numéro de série du pelicano
Referenced by DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CHopper.Init.
bool DeviceLibrary.CccTalk.SimplePoll
Simple poll du périphérique.
Referenced by DeviceLibrary.CCoinValidator.CCoinValidator, DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CHopper.CHopper.
DeviceLibrary.CccTalk.CccTalk()
Construteur de la class
References DeviceLibrary.messagesText.busOKfinded, DeviceLibrary.messagesText.ccTalkInstance, DeviceLibrary.messagesText.erreur, DeviceLibrary.CccTalk.IsCcTalkPort, DeviceLibrary.CccTalk.PortSerie, DeviceLibrary.messagesText.search_ccTalk.
byte DeviceLibrary.CccTalk.GetByte(object header)
Lit un octet dans le périphérique
header Header de la requête La valeur de l'octet retourné est 255la valeur de l'octet demandé
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.messagesText.erreurCmd, DeviceLibrary.messagesText.getByte, DeviceLibrary.CccTalk.IsCmdccTalkSended.
static byte DeviceLibrary.CccTalk.CheckSum(byte[] buffer, byte len)
Retourne le checksum du buffer
buffer Buffer sur lequel le calcul s'effectue len Longeur du buffer
Referenced by DeviceLibrary.CccTalk.IsCmdccTalkSended.
string DeviceLibrary.CccTalk.GetASCII(Header header)
Lit une chaîne ascii dans le périphérique.
header Header de la requête La chaine de caractères demandée
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.messagesText.erreurCmd, DeviceLibrary.messagesText.getText, DeviceLibrary.CccTalk.IsCmdccTalkSended.
bool DeviceLibrary.CccTalk.IsCcTalkPort(string nameOfPort)
Vérifie si un bus ccTalk est branché sur un port série.
nameOfPort Nom du port série true si un bus ccTalk est detecté sur ce port série
References DeviceLibrary.messagesText.erreurPort, DeviceLibrary.CccTalk.PortSerie, DeviceLibrary.messagesText.verifSerialPort.
Referenced by DeviceLibrary.CccTalk.CccTalk.
void DeviceLibrary.CccTalk.ZeroMemory(byte[] buffer, byte len)
Vide le buffer passé en paramètre
buffer Buffer devant être vidé len Longueur du buffer
References DeviceLibrary.messagesText.erreur.
Referenced by DeviceLibrary.CccTalk.IsCmdccTalkSended.
static void DeviceLibrary.CccTalk.ResetCounters()
Remise à zéro des compteurs
References DeviceLibrary.CccTalk.counters, DeviceLibrary.CccTalk.counterSerializer, DeviceLibrary.CccTalk.countersFile.
override void DeviceLibrary.CccTalk.Init()
Initialisation des périphériques ccTalk
bool DeviceLibrary.CccTalk.IsCmdccTalkSended(DefaultDevicesAddress peripherique, object commande, byte lenParam, byte[] parameter, object answer)
Envoie une commande et recoit la réponse
peripherique Adresse du périphérique commande Header de la commande envoyée lenParam Longeur des paramètres parameter Buffer des paramètres answer Objet contenant les paramètres de retour le cas échéant
References DeviceLibrary.CccTalk.CheckSum, DeviceLibrary.messagesText.echo, DeviceLibrary.messagesText.erreur, DeviceLibrary.messagesText.noccTalkDevice, DeviceLibrary.CccTalk.PortSerie, DeviceLibrary.messagesText.readAnswerDevice, DeviceLibrary.messagesText.readEcho, DeviceLibrary.messagesText.sendCmd, DeviceLibrary.CccTalk.sizeOfBufferOut, DeviceLibrary.messagesText.txtAnswer, DeviceLibrary.messagesText.txtMessageSended, DeviceLibrary.CccTalk.verrou, DeviceLibrary.CccTalk.ZeroMemory.
Referenced by DeviceLibrary.CPelicano.ActivateMotor, DeviceLibrary.CHopper.DispenseCoins, DeviceLibrary.CHopper.EnableHopper, DeviceLibrary.CccTalk.GetASCII, DeviceLibrary.CCoinValidator.CCVcreditBuffer.GetBufferCredit, DeviceLibrary.CccTalk.GetByte, DeviceLibrary.CHopper.GetCipherKey, DeviceLibrary.CCoinValidator.CCanal.CCoindID.GetCoinId, DeviceLibrary.CMemoryStorage.GetDataBlock, DeviceLibrary.CMemoryStorage.GetDataStorageAvailability, DeviceLibrary.CHopper.CHopperStatus.GetHopperStatus, DeviceLibrary.CcashReader.GetInhibitMask, DeviceLibrary.CHopper.CHopperVariableSet.GetVariableSet, DeviceLibrary.CCoinValidator.GetVariablesSet, DeviceLibrary.CccTalk.IsDeviceReseted, DeviceLibrary.CHopper.PumpRNG, DeviceLibrary.CMemoryStorage.SetDataBlock, DeviceLibrary.CcashReader.SetInhibitStatus, DeviceLibrary.CcashReader.SetMasterInhibit, DeviceLibrary.CCoinValidator.SetOverrideStatus, DeviceLibrary.CCoinValidator.CCanal.CSorter.SetSorterPath, DeviceLibrary.CHopper.CHopperVariableSet.SetVariable, DeviceLibrary.CHopper.TestHopper, DeviceLibrary.CCoinValidator.TestSolenoid.
bool DeviceLibrary.CccTalk.IsDeviceReseted()
Reset software du périphérique.
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.messagesText.erreurCmd, DeviceLibrary.CccTalk.IsCmdccTalkSended.
Referenced by DeviceLibrary.CCoinValidator.CCoinValidator, DeviceLibrary.CCoinValidator.CheckState, DeviceLibrary.CHopper.CHopper, DeviceLibrary.CHopper.Task.