AtmbTestDevices::FormMain
CDevicesManager AtmbTestDevices.FormMain.deviceManage
Instanciation de la classe principale de la dll
Referenced by AtmbTestDevices.FormMain.ButtonCounters_Click, AtmbTestDevices.FormMain.ButtonHoppers_Click, AtmbTestDevices.FormMain.FormMain_Shown, AtmbTestDevices.FormMain.MsgFromdll.
Form2 AtmbTestDevices.FormMain.form2
Referenced by AtmbTestDevices.FormMain.FormMain_Shown.
bool AtmbTestDevices.FormMain.isMontantPercuReset
Indique si le montant perçu doit être remis à zéro.
Referenced by AtmbTestDevices.FormMain.FormMain_Shown, AtmbTestDevices.FormMain.MsgFromdll, AtmbTestDevices.FormMain.TBAmountToPay_Leave.
int AtmbTestDevices.FormMain.ToDispenseBNR
Montant à distribuer par le BNR
Referenced by AtmbTestDevices.FormMain.BtnBNRDispense_Click, AtmbTestDevices.FormMain.TextBoxBNRDspense_Leave.
uint AtmbTestDevices.FormMain.toLoadInLoader
Nombre de billets dans le loader.
Referenced by AtmbTestDevices.FormMain.ButtonLoaderMeter_Click, AtmbTestDevices.FormMain.TextBoxLoaderNumberBillet_Leave.
int AtmbTestDevices.FormMain.ToPayByClient
Montant à payer
Referenced by AtmbTestDevices.FormMain.MsgFromdll, AtmbTestDevices.FormMain.TBAmountToPay_Leave.
System.ComponentModel.IContainer AtmbTestDevices.FormMain.components
Variable nécessaire au concepteur.
Referenced by AtmbTestDevices.FormMain.Dispose.
System.IO.Ports.SerialPort AtmbTestDevices.FormMain.serialPort
System.Windows.Forms.TextBox AtmbTestDevices.FormMain.tbToPay
Referenced by AtmbTestDevices.FormMain.TBAmountToPay_Leave.
System.Windows.Forms.Label AtmbTestDevices.FormMain.labelAmountToPay
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonExit
System.Windows.Forms.StatusStrip AtmbTestDevices.FormMain.statusStrip
System.Windows.Forms.ToolStripStatusLabel AtmbTestDevices.FormMain.toolStripStatusLabel1
System.Windows.Forms.Label AtmbTestDevices.FormMain.labelAmountReceived
System.Windows.Forms.TextBox AtmbTestDevices.FormMain.tbReceived
System.Windows.Forms.Label AtmbTestDevices.FormMain.labelAmountRemaining
System.Windows.Forms.TextBox AtmbTestDevices.FormMain.tbRemaining
System.Windows.Forms.TextBox AtmbTestDevices.FormMain.tbDenomination
System.Windows.Forms.Label AtmbTestDevices.FormMain.labelDenomination
System.Windows.Forms.ToolStripStatusLabel AtmbTestDevices.FormMain.stripLabelCom
System.Windows.Forms.ToolStripStatusLabel AtmbTestDevices.FormMain.stripLabelCashReaderStatus
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonHoppers
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonCounters
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonRAZCompteurs
System.Windows.Forms.ContextMenuStrip AtmbTestDevices.FormMain.contextMenuStripClear
System.Windows.Forms.ToolStripMenuItem AtmbTestDevices.FormMain.toolStripMenuItem1
System.Windows.Forms.GroupBox AtmbTestDevices.FormMain.groupBoxPieces
System.Windows.Forms.DataGridView AtmbTestDevices.FormMain.dataGridViewCompteurs
Referenced by AtmbTestDevices.FormMain.InitializeComponent.
System.Windows.Forms.DataGridView AtmbTestDevices.FormMain.dataGridViewHopper
Referenced by AtmbTestDevices.FormMain.ButtonHoppers_Click, AtmbTestDevices.FormMain.DataGridViewHopper_CellClick, AtmbTestDevices.FormMain.DataGridViewHopper_CellValueChanged, AtmbTestDevices.FormMain.InitializeComponent, AtmbTestDevices.FormMain.MsgFromdll.
System.Windows.Forms.TextBox AtmbTestDevices.FormMain.tbInfo
System.Windows.Forms.GroupBox AtmbTestDevices.FormMain.groupBox1
System.Windows.Forms.DataGridView AtmbTestDevices.FormMain.dataGridView1
Referenced by AtmbTestDevices.FormMain.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.dataGridViewTextBoxColumn1
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.dataGridViewTextBoxColumn2
System.Windows.Forms.TextBox AtmbTestDevices.FormMain.textBox1
System.Windows.Forms.Button AtmbTestDevices.FormMain.butttonEndofTransacton
System.Windows.Forms.DataGridView AtmbTestDevices.FormMain.dataGridView2
Referenced by AtmbTestDevices.FormMain.InitializeComponent.
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.dataGridViewTextBoxColumn3
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.dataGridViewTextBoxColumn4
System.Windows.Forms.DataGridViewCheckBoxColumn AtmbTestDevices.FormMain.dataGridViewCheckBoxColumn1
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.dataGridViewTextBoxColumn5
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.dataGridViewTextBoxColumn6
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.dataGridViewTextBoxColumn7
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.dataGridViewTextBoxColumn8
System.Windows.Forms.DataGridViewCheckBoxColumn AtmbTestDevices.FormMain.dataGridViewCheckBoxColumn2
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.dataGridViewTextBoxColumn9
System.Windows.Forms.DataGridViewCheckBoxColumn AtmbTestDevices.FormMain.dataGridViewCheckBoxColumn3
System.Windows.Forms.Button AtmbTestDevices.FormMain.BtnDispenseBNR
System.Windows.Forms.TextBox AtmbTestDevices.FormMain.textBoxBnrDispense
Referenced by AtmbTestDevices.FormMain.TextBoxBNRDspense_Leave.
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.Identifiant
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.Valeur
System.Windows.Forms.DataGridViewCheckBoxColumn AtmbTestDevices.FormMain.Present
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.ToDispense
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.Dispensed
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.LevelSW
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.LevelHW
System.Windows.Forms.DataGridViewCheckBoxColumn AtmbTestDevices.FormMain.ToEmpty
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.Reload
System.Windows.Forms.DataGridViewCheckBoxColumn AtmbTestDevices.FormMain.ToLoad
System.Windows.Forms.TextBox AtmbTestDevices.FormMain.textBoxLoaderNumberBilet
Referenced by AtmbTestDevices.FormMain.TextBoxLoaderNumberBillet_Leave.
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonLoaderMeter
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonTrieur
System.Windows.Forms.Label AtmbTestDevices.FormMain.labelCanal
System.Windows.Forms.Label AtmbTestDevices.FormMain.labelPath
System.Windows.Forms.NumericUpDown AtmbTestDevices.FormMain.numericUpDownCanal
Referenced by AtmbTestDevices.FormMain.ButtonTrieur_Click, AtmbTestDevices.FormMain.InitializeComponent.
System.Windows.Forms.NumericUpDown AtmbTestDevices.FormMain.numericUpDownPath
Referenced by AtmbTestDevices.FormMain.InitializeComponent.
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonRetract
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonRollBack
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.Nom
System.Windows.Forms.DataGridViewTextBoxColumn AtmbTestDevices.FormMain.Montant
System.Windows.Forms.DataGridViewCheckBoxColumn AtmbTestDevices.FormMain.RAZ
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonCancel
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonCashBoxRemove
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonLoadRecycler
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonAuditReport
System.Windows.Forms.Button AtmbTestDevices.FormMain.buttonEmptyBnr
AtmbTestDevices.FormMain.FormMain()
Initialise la fenetre principale.
References AtmbTestDevices.FormMain.InitializeComponent.
void AtmbTestDevices.FormMain.BbuttonRollBack_Click(object sender, EventArgs e)
Retourne les billets lus.
sender e
void AtmbTestDevices.FormMain.BtnBNRDispense_Click(object sender, EventArgs e)
Envoie une demande de distribution u BNR
sender e
References AtmbTestDevices.FormMain.ToDispenseBNR.
void AtmbTestDevices.FormMain.Button1_Click(object sender, EventArgs e)
Indique que la caisse à monnaie a été retirée
sender e
void AtmbTestDevices.FormMain.ButtonCancel_Click(object sender, EventArgs e)
void AtmbTestDevices.FormMain.ButtonCounters_Click(object sender, EventArgs e)
Lecture forcée des compteurs.
sender e
References DeviceLibrary.CCoinValidator.canaux, AtmbTestDevices.FormMain.deviceManage, DeviceLibrary.CDevicesManager.Hoppers, DeviceLibrary.CDevicesManager.monnayeur.
Referenced by AtmbTestDevices.FormMain.ButtonHoppers_Click, AtmbTestDevices.FormMain.ButtonRAZCompteurs_Click, AtmbTestDevices.FormMain.MsgFromdll.
void AtmbTestDevices.FormMain.buttonEmptyBnr_Click(object sender, EventArgs e)
Transfert les billets du loader et des recyclers dans la caisse du BNR.
sender e
void AtmbTestDevices.FormMain.ButtonExit_Click(object sender, EventArgs e)
Fonction executée lors du click sur le bouton quitter
sender e
void AtmbTestDevices.FormMain.ButtonFinTrans_Click(object sender, EventArgs e)
Cloture de la transaction en cours.
sender e
void AtmbTestDevices.FormMain.ButtonHoppers_Click(object sender, EventArgs e)
Traitement des hoppers
sender e
References AtmbTestDevices.FormMain.ButtonCounters_Click, AtmbTestDevices.FormMain.dataGridViewHopper, AtmbTestDevices.FormMain.deviceManage, DeviceLibrary.CDevicesManager.Hoppers, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CHopper.name.
void AtmbTestDevices.FormMain.ButtonLoaderMeter_Click(object sender, EventArgs e)
Demande à la dll d'enregister le nombre de billets dans le compteur du loader.
sender e
References AtmbTestDevices.FormMain.toLoadInLoader.
void AtmbTestDevices.FormMain.buttonLoadRecycler_Click(object sender, EventArgs e)
Rechargement recyclers.
sender e
void AtmbTestDevices.FormMain.ButtonRAZCompteurs_Click(object sender, EventArgs e)
Remise à zéro des compteurs.
sender e
References AtmbTestDevices.FormMain.ButtonCounters_Click.
void AtmbTestDevices.FormMain.ButtonRetract_Click(object sender, EventArgs e)
Encaisse les billets présents dans le bezel.
sender e
void AtmbTestDevices.FormMain.ButtonTrieur_Click(object sender, EventArgs e)
Fonction demandant la modification du chemin de sortie.
sender e
References AtmbTestDevices.FormMain.numericUpDownCanal.
void AtmbTestDevices.FormMain.DataGridViewHopper_CellClick(object sender, DataGridViewCellEventArgs e)
Traite les flags dans les colonnes de la grille des hoppers.
sender e
References AtmbTestDevices.FormMain.dataGridViewHopper.
void AtmbTestDevices.FormMain.DataGridViewHopper_CellValueChanged(object sender, DataGridViewCellEventArgs e)
Effectue le traitement des valeurs saisie dans la grille des hoppers.
sender e
References AtmbTestDevices.FormMain.dataGridViewHopper.
void AtmbTestDevices.FormMain.FormMain_FormClosed(object sender, FormClosedEventArgs e)
Quitte l'applciation.
sender e
void AtmbTestDevices.FormMain.FormMain_Shown(object sender, EventArgs e)
AFfiche une fenetre de patience lors de l'affichage de la fenêtre principale. Active la fonction delegate recevant les messages de la dll.
sender e
References AtmbTestDevices.FormMain.deviceManage, AtmbTestDevices.FormMain.form2, AtmbTestDevices.FormMain.isMontantPercuReset, AtmbTestDevices.FormMain.MsgFromdll.
void AtmbTestDevices.FormMain.MsgFromdll(object sender, CEvent.FireEventArg e)
Fonction levée à chaque évenement provenant de la dll
sender e
References DeviceLibrary.CModuleEmptied.amount, AtmbTestDevices.FormMain.ButtonCounters_Click, DeviceLibrary.CEvent.data, AtmbTestDevices.FormMain.dataGridViewHopper, AtmbTestDevices.FormMain.deviceManage, DeviceLibrary.CDevicesManager.Hoppers, AtmbTestDevices.FormMain.isMontantPercuReset, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CEvent.nameOfDevice, AtmbTestDevices.FormMain.ToPayByClient, DeviceLibrary.CInserted.TotalAmount.
Referenced by AtmbTestDevices.FormMain.FormMain_Shown.
void AtmbTestDevices.FormMain.TBAmountToPay_Enter(object sender, EventArgs e)
Vide le champ de saisie.
sender e
void AtmbTestDevices.FormMain.TBAmountToPay_Leave(object sender, EventArgs e)
Fonction executée à la fin de la saisie du montant à payer
sender e
References AtmbTestDevices.FormMain.isMontantPercuReset, AtmbTestDevices.FormMain.tbToPay, AtmbTestDevices.FormMain.ToPayByClient.
void AtmbTestDevices.FormMain.TextBoxBNRDispense_Enter(object sender, EventArgs e)
Vide le champ de saisie du montant à distribuer par le BNR lorsque le champ recoit le focus.
sender e
void AtmbTestDevices.FormMain.TextBoxBNRDspense_Leave(object sender, EventArgs e)
Vérifie et reformat la saisie lorsque le champ de saisie pert le focus.
sender e
References AtmbTestDevices.FormMain.textBoxBnrDispense, AtmbTestDevices.FormMain.ToDispenseBNR.
void AtmbTestDevices.FormMain.TextBoxLoaderNumberBillet_Enter(object sender, EventArgs e)
Vide le champ du nombre de billets à enregistrer dans les compteurs du loader.
sender e
void AtmbTestDevices.FormMain.TextBoxLoaderNumberBillet_Leave(object sender, EventArgs e)
Vérifie et format le nombre de billets à enregistrer dans le compteur du loader.
sender e
References AtmbTestDevices.FormMain.textBoxLoaderNumberBilet, AtmbTestDevices.FormMain.toLoadInLoader.
void AtmbTestDevices.FormMain.ToolStripMenuItem1_Click(object sender, EventArgs e)
Efface les logs.
sender e
void AtmbTestDevices.FormMain.InitializeComponent()
Méthode requise pour la prise en charge du concepteur - ne modifiez pas le contenu de cette méthode avec l'éditeur de code.
References AtmbTestDevices.FormMain.dataGridView1, AtmbTestDevices.FormMain.dataGridView2, AtmbTestDevices.FormMain.dataGridViewCompteurs, AtmbTestDevices.FormMain.dataGridViewHopper, AtmbTestDevices.FormMain.numericUpDownCanal, AtmbTestDevices.FormMain.numericUpDownPath.
Referenced by AtmbTestDevices.FormMain.FormMain.
override void AtmbTestDevices.FormMain.Dispose(bool disposing)
Nettoyage des ressources utilisées.
<bufferParam name="disposing">true si les ressources managées doivent être supprimées ; sinon, false.</bufferParam>
References AtmbTestDevices.FormMain.components.