DeviceLibrary::CDevicesManager
readonly XmlDocument DeviceLibrary.CDevicesManager.ParametersFile
Instance de la classe XmlDocument permettant la lecture des fichiers XML.
readonly CBNR_CPI DeviceLibrary.CDevicesManager.bnX
Instance du BNR
Referenced by DeviceLibrary.CDevicesManager.BNRBillRetract, DeviceLibrary.CDevicesManager.BNRBillRollBack, DeviceLibrary.CDevicesManager.BNRReloadRecycler, DeviceLibrary.CDevicesManager.BNRSetLoaderMeter, DeviceLibrary.CDevicesManager.BNRTransfertLoaderRecyclersInCB, DeviceLibrary.CDevicesManager.CancelTransaction, DeviceLibrary.CDevicesManager.CDevicesManager, DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CDevicesManager.Task.
readonly Thread DeviceLibrary.CDevicesManager.msgTask
Thread de la classe principale.
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager.
Logger DeviceLibrary.CDevicesManager.Log
Instance le la class Logger utilisée pour les logs.
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager.
int DeviceLibrary.CDevicesManager.ToPay
Variable contenant le montant à payer.
Referenced by DeviceLibrary.CDevicesManager.BeginTransaction, DeviceLibrary.CDevicesManager.BNRBillRollBack, DeviceLibrary.CDevicesManager.CancelTransaction, DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CPelicano.Task, DeviceLibrary.CDevicesManager.Task.
CCashReceived DeviceLibrary.CDevicesManager.cashReceived
Instance de la classe CCashReceived.
Referenced by DeviceLibrary.CDevicesManager.BeginTransaction, DeviceLibrary.CDevicesManager.OnCashClose, DeviceLibrary.CDevicesManager.Task.
string DeviceLibrary.CDevicesManager.ParamFileName
Nom du fichier des paramètres.
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager.
string DeviceLibrary.CDevicesManager.alternateDevise
Seconde devise acceptée.
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager.
string DeviceLibrary.CDevicesManager.mainDevise
Devise principale
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager, DeviceLibrary.CBNR_CPI.Task.
decimal DeviceLibrary.CDevicesManager.tauxDeChange
Taux de conversion à appliquer pour la devise secondaire.
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager.
List<CHopper> DeviceLibrary.CDevicesManager.Hoppers
Liste des hoppers
Referenced by AtmbTestDevices.FormMain.ButtonCounters_Click, AtmbTestDevices.FormMain.ButtonHoppers_Click, DeviceLibrary.CDevicesManager.ccTalkCountersResets, DeviceLibrary.CDevicesManager.CDevicesManager, DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CDevicesManager.Dispose, AtmbTestDevices.FormMain.MsgFromdll, DeviceLibrary.CDevicesManager.ReadParamHopper.
CCoinValidator DeviceLibrary.CDevicesManager.monnayeur
Instance du monnayeur
Referenced by DeviceLibrary.CDevicesManager.BeginTransaction, DeviceLibrary.CDevicesManager.BNRCashBoxRemoved, AtmbTestDevices.FormMain.ButtonCounters_Click, DeviceLibrary.CDevicesManager.CDevicesManager, DeviceLibrary.CDevicesManager.Task.
FireEventHandler DeviceLibrary.CDevicesManager.FireEvent
Evenement levant un appel à la fonction déléguée.
Referenced by DeviceLibrary.CDevicesManager.OnBNRDispensed, DeviceLibrary.CDevicesManager.OnBNRErreur, DeviceLibrary.CDevicesManager.OnbnrModuleReinsere, DeviceLibrary.CDevicesManager.OnBNRResetModule, DeviceLibrary.CDevicesManager.OnBRNModuleRemoved, DeviceLibrary.CDevicesManager.OnCashBoxRemoved, DeviceLibrary.CDevicesManager.OnCashClose, DeviceLibrary.CDevicesManager.OnCashOpen, DeviceLibrary.CDevicesManager.OnCVError, DeviceLibrary.CDevicesManager.OnDllReady, DeviceLibrary.CDevicesManager.OnHopperDispensed, DeviceLibrary.CDevicesManager.OnHopperEmptied, DeviceLibrary.CDevicesManager.OnHopperError, DeviceLibrary.CDevicesManager.OnHopperHardLevelChanged, DeviceLibrary.CDevicesManager.OnHopperSoftLevelChanged, DeviceLibrary.CDevicesManager.OnModuleEmptied, DeviceLibrary.CDevicesManager.OnMoneyReceived.
byte [] DeviceLibrary.CDevicesManager.EnableChannelsCV
Masque des canaux activés.
Referenced by DeviceLibrary.CCoinValidator.Init.
delegate void DeviceLibrary.CDevicesManager.FireEventHandler(object sender, CEvent.FireEventArg e)
Prototype de la fonctio delegate recevant les messages de la dll.
sender e
DeviceLibrary.CDevicesManager.CDevicesManager()
Constructeur de la classe principale
References DeviceLibrary.CDevicesManager.alternateDevise, DeviceLibrary.CDevicesManager.bnX, DeviceLibrary.messagesText.callDll, DeviceLibrary.CccTalk.counters, DeviceLibrary.CccTalk.counterSerializer, DeviceLibrary.CccTalk.countersFile, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevice.eventListLock, DeviceLibrary.CccTalk.fileCounterName, DeviceLibrary.CDevicesManager.Hoppers, DeviceLibrary.CDevicesManager.Log, DeviceLibrary.CDevicesManager.mainDevise, DeviceLibrary.CDevicesManager.monnayeur, DeviceLibrary.CDevicesManager.msgTask, DeviceLibrary.CDevicesManager.ParamFileName, DeviceLibrary.CccTalk.ProductCode, DeviceLibrary.CDevicesManager.ReadParamHopper, DeviceLibrary.CDevicesManager.SetSortersAndHoppersToLoad, DeviceLibrary.CDevicesManager.Task, DeviceLibrary.CDevicesManager.tauxDeChange.
void DeviceLibrary.CDevicesManager.BeginTransaction(int value)
Ouvre une transaction le montant à payer.
value montant en centimes à payer Provoque l'ouverture des moyens de paiement.
References DeviceLibrary.CDevicesManager.cashReceived, DeviceLibrary.CDevice.denominationInserted, DeviceLibrary.CDevicesManager.EndTransaction, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevice.eventListLock, DeviceLibrary.CDevicesManager.monnayeur, DeviceLibrary.CDevicesManager.ToPay, DeviceLibrary.CInserted.TotalAmount.
Referenced by DeviceLibrary.CDevicesManager.BNRBillRollBack.
void DeviceLibrary.CDevicesManager.BNRBillRetract()
Reupère les billets présents dans le bezel.
References DeviceLibrary.CBNR_CPI.bnr, DeviceLibrary.CDevicesManager.bnX, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CBNR_CPI.State.
void DeviceLibrary.CDevicesManager.BNRBillRollBack()
Retourne les billets e escrow.
References DeviceLibrary.CDevicesManager.BeginTransaction, DeviceLibrary.CBNR_CPI.bnr, DeviceLibrary.CDevicesManager.bnX, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CBNR_CPI.State, DeviceLibrary.CDevicesManager.ToPay.
void DeviceLibrary.CDevicesManager.BNRCashBoxRemoved()
Remise à zéro des compteurs de la caisse
References DeviceLibrary.CCoinValidator.canaux, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevice.eventListLock, DeviceLibrary.CDevicesManager.monnayeur.
void DeviceLibrary.CDevicesManager.BNRDispense(int amount)
Envoi une demande de distribution au BNR
amount Montant à distribuer.
void DeviceLibrary.CDevicesManager.BNRReloadRecycler()
Fonction permettant le rechargment des recyclers.
References DeviceLibrary.CBNR_CPI.bnr, DeviceLibrary.CDevicesManager.bnX, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevice.IsPresent.
void DeviceLibrary.CDevicesManager.BNRSetLoaderMeter(uint numberOfBill)
Fixe le compteur de billets contenus dans le loader.
numberOfBill Nombre de billets dans le loader.
References DeviceLibrary.CBNR_CPI.bnr, DeviceLibrary.CDevicesManager.bnX, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevice.IsPresent.
void DeviceLibrary.CDevicesManager.BNRTransfertLoaderRecyclersInCB()
Transfert les billets du loader et des recyclers dans la caisse du BNR.
References DeviceLibrary.CBNR_CPI.bnr, DeviceLibrary.CDevicesManager.bnX, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevice.IsPresent.
void DeviceLibrary.CDevicesManager.CancelTransaction()
Abandonne la transaction et retourne le montant introduit
References DeviceLibrary.CBNR_CPI.bnr, DeviceLibrary.CDevicesManager.bnX, DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CDevicesManager.EndTransaction, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CBNR_CPI.State, DeviceLibrary.CDevicesManager.ToPay.
void DeviceLibrary.CDevicesManager.ccTalkCountersResets()
Remise à zéro des compteurs.
References DeviceLibrary.CDevicesManager.Hoppers.
void DeviceLibrary.CDevicesManager.Dispose()
Libère les ressources.
Referenced by DeviceLibrary.CDevicesManager.~CDevicesManager.
void DeviceLibrary.CDevicesManager.EndTransaction()
Cloture la transaction en cours
References DeviceLibrary.CDevice.eventListLock.
Referenced by DeviceLibrary.CDevicesManager.BeginTransaction, DeviceLibrary.CDevicesManager.CancelTransaction, DeviceLibrary.CDevicesManager.OnDllReady, DeviceLibrary.CDevicesManager.Task.
string DeviceLibrary.CDevicesManager.GetSerialPort()
Renvoi le nom du port série utilisé par le bus ccTalk
References DeviceLibrary.CccTalk.PortSerie.
void DeviceLibrary.CDevicesManager.SetSorterPath(byte canal, byte sorter)
Modifie le le chemin de tri du canal.
canal Canal du monnayeur sorter chemin du trieur
References DeviceLibrary.messagesText.erreur.
void DeviceLibrary.CDevicesManager.ChangeBack()
Effectue le rendu monnaie.
References DeviceLibrary.CBNR_CPI.bnr, DeviceLibrary.CBNR_CPI.BnrDefaultOperationTimeOutInMS, DeviceLibrary.CDevicesManager.bnX, DeviceLibrary.CHopper.CoinsToDistribute, DeviceLibrary.CHopper.CoinValue, DeviceLibrary.CHopper.deviceLevel, DeviceLibrary.messagesText.erreur, DeviceLibrary.CHopper.CLevel.hardLevel, DeviceLibrary.CDevicesManager.Hoppers, DeviceLibrary.CBNR_CPI.isDispensable, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CHopper.CLevel.softLevel, DeviceLibrary.CBNR_CPI.State, DeviceLibrary.CHopper.State, DeviceLibrary.CDevicesManager.ToPay.
Referenced by DeviceLibrary.CDevicesManager.CancelTransaction, DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnBNRDispensed(CEvent evenment)
Le BNR a distribué des billets.
evenment
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnBNRErreur(CEvent evenement)
Evénement levé quand une erreur s'est produte sur le BNR.
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnbnrModuleReinsere(CEvent evenement)
Evenment levé quand un module est réinséré.
evenement
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnBNRResetModule(CEvent evenement)
Indique que le module est remis à zéro.
evenement
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnBRNModuleRemoved(CEvent evenement)
Evenement levé si un module est retiré du BNR.
evenement
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnCashBoxRemoved(CEvent evenment)
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnCashClose()
Evénement levé lors de la cloture de la transaction.
References DeviceLibrary.CDevicesManager.cashReceived, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnCashOpen()
Evénement levé lors de l'ouverture des moyens de paiement.
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnCVError(CEvent evenement)
Evénement levé lors de la détection d'une erreur sur le monnayeur.
evenement
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnDllReady()
Evénement levé lorsque la dll est prête.
References DeviceLibrary.CDevicesManager.EndTransaction, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnHopperDispensed(CEvent evenement)
Evénement levé lorsque la distribution est terminée.
evenement
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnHopperEmptied(CEvent evenement)
Evénement levé lorsque le hopper est vidé.
evenement
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnHopperError(CEvent evenement)
Evéenemnt levé lorsqu'une error est detectée sur un hopper.
evenement
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnHopperHardLevelChanged(CEvent evenement)
Evénement levé lorsqu'un changement d'état d'une sonde de niveau d'un hopper est detecté.
evenement
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnHopperSoftLevelChanged(CEvent evenement)
Evénement levé lorsqu'un niveau de pièces atteint une des limites fixées pour le hopper
evenement
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnModuleEmptied(CEvent evenement)
Evenement levé pour la fin du vidage d'un module.
evenement
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.OnMoneyReceived(CEvent evenement)
Evémenment levé lors de l'introduction d'une pièce.
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.FireEvent.
Referenced by DeviceLibrary.CDevicesManager.Task.
void DeviceLibrary.CDevicesManager.ReadParamHopper()
Cette fonction lit les paramètres des hoppers.
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevicesManager.Hoppers.
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager.
void DeviceLibrary.CDevicesManager.SetSortersAndHoppersToLoad()
Cette fonction lit, pour chaque canal, les chemins de tris et les hoppers devant être rechargés lors de l'insertion d'une pièce dans le monnayeur
References DeviceLibrary.messagesText.erreur.
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager.
void DeviceLibrary.CDevicesManager.Task()
Tâche principale de la dll
References DeviceLibrary.CDevicesManager.bnX, DeviceLibrary.CDevicesManager.cashReceived, DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CDevice.denominationInserted, DeviceLibrary.CDevicesManager.EndTransaction, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevice.eventListLock, DeviceLibrary.CDevice.eventsList, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CDevicesManager.monnayeur, DeviceLibrary.CDevicesManager.OnBNRDispensed, DeviceLibrary.CDevicesManager.OnBNRErreur, DeviceLibrary.CDevicesManager.OnbnrModuleReinsere, DeviceLibrary.CDevicesManager.OnBNRResetModule, DeviceLibrary.CDevicesManager.OnBRNModuleRemoved, DeviceLibrary.CDevicesManager.OnCashBoxRemoved, DeviceLibrary.CDevicesManager.OnCashClose, DeviceLibrary.CDevicesManager.OnCashOpen, DeviceLibrary.CDevicesManager.OnCVError, DeviceLibrary.CDevicesManager.OnDllReady, DeviceLibrary.CDevicesManager.OnHopperDispensed, DeviceLibrary.CDevicesManager.OnHopperEmptied, DeviceLibrary.CDevicesManager.OnHopperError, DeviceLibrary.CDevicesManager.OnHopperHardLevelChanged, DeviceLibrary.CDevicesManager.OnHopperSoftLevelChanged, DeviceLibrary.CDevicesManager.OnModuleEmptied, DeviceLibrary.CDevicesManager.OnMoneyReceived, DeviceLibrary.CBNR_CPI.State, DeviceLibrary.CDevicesManager.ToPay, DeviceLibrary.CInserted.TotalAmount.
Referenced by DeviceLibrary.CDevicesManager.CDevicesManager.
DeviceLibrary.CDevicesManager.~CDevicesManager()
Destructeur
References DeviceLibrary.CDevicesManager.Dispose.
void DeviceLibrary.CDevicesManager.Dispose(bool disposing)
Fonction libérant les ressources
References DeviceLibrary.CDevicesManager.Hoppers.