DeviceLibrary::CHopper::CHopperVariableSet
CoinMode
Plusieurs pièces peuvent être distribuées en 1 opération.
Variable
Limit de courant avant d'inverser la rotation du moteur
readonly CHopper DeviceLibrary.CHopper.CHopperVariableSet.Owner
Hopper propriétaire de l'instance.
Referenced by DeviceLibrary.CHopper.CHopperVariableSet.CHopperVariableSet, DeviceLibrary.CHopper.CHopperVariableSet.GetVariableSet, DeviceLibrary.CHopper.CHopperVariableSet.SetVariable.
byte [] DeviceLibrary.CHopper.CHopperVariableSet.variableSetToRead
Referenced by DeviceLibrary.CHopper.CHopperVariableSet.GetVariableSetToRead, DeviceLibrary.CHopper.CHopperVariableSet.SetVariableSetToRead.
byte DeviceLibrary.CHopper.CHopperVariableSet.ConnectorAddress
Lecture de l'adresse physique du hopper
double DeviceLibrary.CHopper.CHopperVariableSet.CurrentLimit
Lecture et conversion de la limite de courant
double DeviceLibrary.CHopper.CHopperVariableSet.Maxcurrent
Lecture et conversion du courant maximum
byte DeviceLibrary.CHopper.CHopperVariableSet.MotorStopDelay
Lecture du delai pour arrêter le moteur.
byte DeviceLibrary.CHopper.CHopperVariableSet.PayoutDelayTO
Lecture du delay pour la distribution d'un pièce.
double DeviceLibrary.CHopper.CHopperVariableSet.Tension
Lecture et conversion de la tension maximum.
DeviceLibrary.CHopper.CHopperVariableSet.CHopperVariableSet(CHopper owner)
Consructeur
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CHopper.CHopperVariableSet.Owner, DeviceLibrary.CHopper.CHopperVariableSet.SetVariableSetToRead.
void DeviceLibrary.CHopper.CHopperVariableSet.GetVariableSet()
Lecture des variables.
References DeviceLibrary.CHopper.AddressBaseHoper, DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CHopper.CHopperVariableSet.GetVariableSetToRead, DeviceLibrary.CccTalk.IsCmdccTalkSended, DeviceLibrary.CHopper.CHopperVariableSet.Owner.
Referenced by DeviceLibrary.CHopper.CHopperVariableSet.GetVariable.
byte [] DeviceLibrary.CHopper.CHopperVariableSet.GetVariableSetToRead()
Buffer du résultat de la commande de lecture des variables du hopper.
References DeviceLibrary.CHopper.CHopperVariableSet.variableSetToRead.
Referenced by DeviceLibrary.CHopper.CHopperVariableSet.GetVariable, DeviceLibrary.CHopper.CHopperVariableSet.GetVariableSet.
void DeviceLibrary.CHopper.CHopperVariableSet.SetVariable(double currentLimit, byte motorStopDelay, byte payoutTO, CoinMode singleCoinMode)
Enregistrement des variables
currentLimit Limit de courant avant l'inversion de la rotaiton motorStopDelay Delai pour arrêter le moteur après la distribution. payoutTO Le délai maximum pour la distribution d'une pièce. singleCoinMode Single coin ou non.
References DeviceLibrary.CccTalk.DeviceAddress, DeviceLibrary.messagesText.erreur, DeviceLibrary.CccTalk.IsCmdccTalkSended, DeviceLibrary.CHopper.CHopperVariableSet.Owner.
void DeviceLibrary.CHopper.CHopperVariableSet.SetVariableSetToRead(byte[] value)
Buffer du résultat de la commande de lecture des variables du hopper.
References DeviceLibrary.CHopper.CHopperVariableSet.variableSetToRead.
Referenced by DeviceLibrary.CHopper.CHopperVariableSet.CHopperVariableSet.
byte DeviceLibrary.CHopper.CHopperVariableSet.GetVariable(Variable variable)
Lecture d'une variable
variable variable demandée Valeur de la variable demandée
References DeviceLibrary.CHopper.CHopperVariableSet.GetVariableSet, DeviceLibrary.CHopper.CHopperVariableSet.GetVariableSetToRead.