DeviceLibrary::CBNR_CPI
Errortype
Billet bloqué dans le BNR.
Etat
Initialisation du BNR.
const int DeviceLibrary.CBNR_CPI.BnrResetTimeOutInMS
Délai maximum accordé pour effectur un reset
Referenced by DeviceLibrary.CBNR_CPI.Task.
int DeviceLibrary.CBNR_CPI.amountToDispense
int DeviceLibrary.CBNR_CPI.divider
Cerror DeviceLibrary.CBNR_CPI.errorInfo
Instance de la class Cerror.
Referenced by DeviceLibrary.CBNR_CPI.Bnr_OperationCompletedEvent, DeviceLibrary.CBNR_CPI.HardwareError, DeviceLibrary.CBNR_CPI.Init, DeviceLibrary.CBNR_CPI.Task.
bool DeviceLibrary.CBNR_CPI.isCashPresent
Flag indiquant si les billets sont présentés à l'usager.
Referenced by DeviceLibrary.CBNR_CPI.Retract, DeviceLibrary.CBNR_CPI.StatusOccured, DeviceLibrary.CBNR_CPI.Task.
bool DeviceLibrary.CBNR_CPI.isCashTaken
Flag indiquant si les billets ont été repris.
Referenced by DeviceLibrary.CBNR_CPI.RollBack, DeviceLibrary.CBNR_CPI.StatusOccured.
bool DeviceLibrary.CBNR_CPI.isLoaderMetersUpdade
Flag indiauqnt si les compteurs du loader on été mis à jour.
Referenced by DeviceLibrary.CBNR_CPI.Init, DeviceLibrary.CBNR_CPI.StatusOccured, DeviceLibrary.CBNR_CPI.Task.
Mei.Bnr.CashUnit.LogicalCashUnit [] DeviceLibrary.CBNR_CPI.listLCU
Liste contenant la liste des unités logiques.
Referenced by DeviceLibrary.CBNR_CPI.StatusOccured, DeviceLibrary.CBNR_CPI.Task.
List<CModulePosition> DeviceLibrary.CBNR_CPI.listModulePosition
Liste contenant l'état des modules.
Referenced by DeviceLibrary.CBNR_CPI.Bnr_OperationCompletedEvent, DeviceLibrary.CBNR_CPI.CBNR_CPI, DeviceLibrary.CBNR_CPI.StatusOccured, DeviceLibrary.CBNR_CPI.Task.
Etat DeviceLibrary.CBNR_CPI.state
const int DeviceLibrary.CBNR_CPI.BnrDefaultOperationTimeOutInMS
Delain maximum pour effectuer une opération.
Referenced by DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CBNR_CPI.Retract, DeviceLibrary.CBNR_CPI.RollBack, DeviceLibrary.CBNR_CPI.Task.
CModuleEmptied DeviceLibrary.CBNR_CPI.moduleEmptied
Referenced by DeviceLibrary.CBNR_CPI.Task.
Bnr DeviceLibrary.CBNR_CPI.bnr
Instance du bnr.
Referenced by DeviceLibrary.CDevicesManager.BNRBillRetract, DeviceLibrary.CDevicesManager.BNRBillRollBack, DeviceLibrary.CDevicesManager.BNRReloadRecycler, DeviceLibrary.CDevicesManager.BNRSetLoaderMeter, DeviceLibrary.CDevicesManager.BNRTransfertLoaderRecyclersInCB, DeviceLibrary.CDevicesManager.CancelTransaction, DeviceLibrary.CBNR_CPI.CBNR_CPI, DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CBNR_CPI.CheckAndDispense, DeviceLibrary.CBNR_CPI.HardwareError, DeviceLibrary.CBNR_CPI.RollBack, DeviceLibrary.CBNR_CPI.Task.
AutoResetEvent DeviceLibrary.CBNR_CPI.ev
Evénement permettant de gérer les function asynchrone.
Referenced by DeviceLibrary.CBNR_CPI.CBNR_CPI, DeviceLibrary.CBNR_CPI.Task.
bool DeviceLibrary.CBNR_CPI.isDispensable
Indique si la demande de denomination est possible.
Referenced by DeviceLibrary.CBNR_CPI.Bnr_OperationCompletedEvent, DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CBNR_CPI.CheckAndDispense, DeviceLibrary.CBNR_CPI.Task.
bool DeviceLibrary.CBNR_CPI.isReloadInProgress
Flag indiquant que la recharge des recyclers est en cours.
Referenced by DeviceLibrary.CBNR_CPI.Bnr_OperationCompletedEvent, DeviceLibrary.CBNR_CPI.Init, DeviceLibrary.CBNR_CPI.Reloadrecycler, DeviceLibrary.CBNR_CPI.Task.
readonly Thread DeviceLibrary.CBNR_CPI.bnrTask
Thread utilisé pour le BNR
Referenced by DeviceLibrary.CBNR_CPI.CBNR_CPI.
uint DeviceLibrary.CBNR_CPI.loaderMeter
Indique le nombre de billets à enregister pour le loader.
Referenced by DeviceLibrary.CBNR_CPI.Task.
override string DeviceLibrary.CBNR_CPI.Manufacturer
Retourne l'identifiant du fabricant.
override string DeviceLibrary.CBNR_CPI.ProductCode
Code produit du périphérique.
int DeviceLibrary.CBNR_CPI.Divider
Montant du billet de plus faible valeur;
Referenced by DeviceLibrary.CBNR_CPI.Task.
Etat DeviceLibrary.CBNR_CPI.State
Etat de la machine d'état gérant le BNR.
Referenced by DeviceLibrary.CDevicesManager.BNRBillRetract, DeviceLibrary.CDevicesManager.BNRBillRollBack, DeviceLibrary.CDevicesManager.CancelTransaction, DeviceLibrary.CBNR_CPI.CBNR_CPI, DeviceLibrary.CDevicesManager.ChangeBack, DeviceLibrary.CBNR_CPI.CheckAndDispense, DeviceLibrary.CBNR_CPI.Empty, DeviceLibrary.CBNR_CPI.Reloadrecycler, DeviceLibrary.CBNR_CPI.StatusOccured, DeviceLibrary.CDevicesManager.Task, DeviceLibrary.CBNR_CPI.Task.
int DeviceLibrary.CBNR_CPI.AmountToDispense
Montant à distribuer ou dont on veur vérifier la disponibilité.
Referenced by DeviceLibrary.CBNR_CPI.CheckAndDispense, DeviceLibrary.CBNR_CPI.Task.
int DeviceLibrary.CBNR_CPI.SearchDivider
Recherche la plus petite denomination disponible.
Referenced by DeviceLibrary.CBNR_CPI.Task.
DeviceLibrary.CBNR_CPI.CBNR_CPI()
Constructeur
References DeviceLibrary.CBNR_CPI.bnr, DeviceLibrary.CBNR_CPI.bnrTask, DeviceLibrary.messagesText.erreur, DeviceLibrary.CBNR_CPI.ev, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CBNR_CPI.listModulePosition, DeviceLibrary.CBNR_CPI.State, DeviceLibrary.CBNR_CPI.Task.
void DeviceLibrary.CBNR_CPI.CheckAndDispense(int amount)
Vérifie la possibilité de distribuer le montant indiqué en paramètre et le distribue le cas échéant.
amount Montant à distribuer.
References DeviceLibrary.CBNR_CPI.AmountToDispense, DeviceLibrary.CBNR_CPI.bnr, DeviceLibrary.messagesText.erreur, DeviceLibrary.CBNR_CPI.isDispensable, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CBNR_CPI.State.
void DeviceLibrary.CBNR_CPI.Empty()
Vide les recyclers et le loader dans la caisse.
References DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CBNR_CPI.State.
Referenced by DeviceLibrary.CBNR_CPI.Bnr_OperationCompletedEvent.
override void DeviceLibrary.CBNR_CPI.Init()
Initialisation de la classe du BNR.
References DeviceLibrary.CBNR_CPI.Bnr_OperationCompletedEvent, DeviceLibrary.CBNR_CPI.CashOccured, DeviceLibrary.messagesText.erreur, DeviceLibrary.CBNR_CPI.errorInfo, DeviceLibrary.CBNR_CPI.IntermediateOccured, DeviceLibrary.CBNR_CPI.isLoaderMetersUpdade, DeviceLibrary.CBNR_CPI.isReloadInProgress, DeviceLibrary.CBNR_CPI.StatusOccured.
Referenced by DeviceLibrary.CBNR_CPI.Task.
void DeviceLibrary.CBNR_CPI.Reloadrecycler()
Active la recharge des recyclers.
References DeviceLibrary.messagesText.erreur, DeviceLibrary.CBNR_CPI.isReloadInProgress, DeviceLibrary.CBNR_CPI.State.
override void DeviceLibrary.CBNR_CPI.Task()
Machine d'état du BNR.
References DeviceLibrary.CBNR_CPI.AmountToDispense, DeviceLibrary.CBNR_CPI.bnr, DeviceLibrary.CBNR_CPI.BnrDefaultOperationTimeOutInMS, DeviceLibrary.CBNR_CPI.BnrResetTimeOutInMS, DeviceLibrary.CBNR_CPI.Divider, DeviceLibrary.messagesText.erreur, DeviceLibrary.CBNR_CPI.errorInfo, DeviceLibrary.CBNR_CPI.ev, DeviceLibrary.CDevice.eventListLock, DeviceLibrary.CBNR_CPI.Init, DeviceLibrary.CBNR_CPI.isCashPresent, DeviceLibrary.CBNR_CPI.isDispensable, DeviceLibrary.CBNR_CPI.isLoaderMetersUpdade, DeviceLibrary.CDevice.IsPresent, DeviceLibrary.CBNR_CPI.isReloadInProgress, DeviceLibrary.CBNR_CPI.listLCU, DeviceLibrary.CBNR_CPI.listModulePosition, DeviceLibrary.CBNR_CPI.loaderMeter, DeviceLibrary.CDevicesManager.mainDevise, DeviceLibrary.CBNR_CPI.moduleEmptied, DeviceLibrary.CBNR_CPI.CModulePosition.moduleName, DeviceLibrary.CBNR_CPI.Retract, DeviceLibrary.CBNR_CPI.RollBack, DeviceLibrary.CBNR_CPI.SearchDivider, DeviceLibrary.CBNR_CPI.State.
Referenced by DeviceLibrary.CBNR_CPI.CBNR_CPI.
static void DeviceLibrary.CBNR_CPI.Bnr_OperationCompletedEvent(int identificationId, OperationId operationId, BnrXfsErrorCode result, BnrXfsErrorCode extendedResult, object data)
Function delegate levée à la fin du opération asynchrone.
identificationId Numéro de l'opération. operationId Type d'opération. result Resultat de l'opération. extendedResult Compleément d'information le cas échéant. data Information retournée par l'opération, Le type dépend de l'opéation.
References DeviceLibrary.CDevice.denominationInserted, DeviceLibrary.CBNR_CPI.Empty, DeviceLibrary.messagesText.erreur, DeviceLibrary.CBNR_CPI.errorInfo, DeviceLibrary.CDevice.eventListLock, DeviceLibrary.CBNR_CPI.HardwareError, DeviceLibrary.CBNR_CPI.isDispensable, DeviceLibrary.CBNR_CPI.CModulePosition.isReinserted, DeviceLibrary.CBNR_CPI.isReloadInProgress, DeviceLibrary.CBNR_CPI.listModulePosition, DeviceLibrary.CBNR_CPI.CModulePosition.moduleName, DeviceLibrary.CInserted.ValeurCent.
Referenced by DeviceLibrary.CBNR_CPI.Init.
static void DeviceLibrary.CBNR_CPI.CashOccured(XfsCashOrder cashInOrder)
Levée pour une opération sur un billet.
cashInOrder
Referenced by DeviceLibrary.CBNR_CPI.Init.
static void DeviceLibrary.CBNR_CPI.HardwareError(DeviceStatus deviceStatus)
Recherche de l'erreur et du module en erreur
References DeviceLibrary.CBNR_CPI.bnr, DeviceLibrary.CBNR_CPI.errorInfo, DeviceLibrary.CDevice.eventListLock.
Referenced by DeviceLibrary.CBNR_CPI.Bnr_OperationCompletedEvent, DeviceLibrary.CBNR_CPI.StatusOccured.
static void DeviceLibrary.CBNR_CPI.IntermediateOccured(int identificationId, OperationId operationId, IntermediateEvents result, object data)
Levée pour un évenment intermédiaure durant une opération .
identificationId operationId result data
Referenced by DeviceLibrary.CBNR_CPI.Init.
static void DeviceLibrary.CBNR_CPI.RollBack()
Retourne les billets en escrow.
References DeviceLibrary.CBNR_CPI.bnr, DeviceLibrary.CBNR_CPI.BnrDefaultOperationTimeOutInMS, DeviceLibrary.messagesText.erreur, DeviceLibrary.CBNR_CPI.isCashTaken.
Referenced by DeviceLibrary.CBNR_CPI.Task.
static void DeviceLibrary.CBNR_CPI.StatusOccured(StatusChanged status, BnrXfsErrorCode result, BnrXfsErrorCode extendedResult, object Data)
Levée lors d'un changement d'état à eu lieu.
status result extendedResult Data
References DeviceLibrary.CDevice.denominationInserted, DeviceLibrary.messagesText.erreur, DeviceLibrary.CDevice.eventListLock, DeviceLibrary.CBNR_CPI.HardwareError, DeviceLibrary.CBNR_CPI.isCashPresent, DeviceLibrary.CBNR_CPI.isCashTaken, DeviceLibrary.CBNR_CPI.isLoaderMetersUpdade, DeviceLibrary.CBNR_CPI.CModulePosition.isPresent, DeviceLibrary.CBNR_CPI.listLCU, DeviceLibrary.CBNR_CPI.listModulePosition, DeviceLibrary.CBNR_CPI.CModulePosition.moduleName, DeviceLibrary.CBNR_CPI.State, DeviceLibrary.CInserted.ValeurCent.
Referenced by DeviceLibrary.CBNR_CPI.Init.
void DeviceLibrary.CBNR_CPI.Retract()
Renvoi en caisse les billets présentés non pris.
References DeviceLibrary.CBNR_CPI.BnrDefaultOperationTimeOutInMS, DeviceLibrary.messagesText.erreur, DeviceLibrary.CBNR_CPI.isCashPresent.
Referenced by DeviceLibrary.CBNR_CPI.Task.