namespace DeviceLibrary
{
    public partial class CCoinValidator : CcashReader
    {
        public enum CVErrorCodes  : byte
        {
            NULL = 0,
            REJECTCOIN = 1,
            INHIBITEDCOIN = 2,
            MULTIPLEWINDOWS = 3,
            WAKEUP_TO = 4,
            VALIDATION_TO = 5,
            CREDITSENSOR_TO = 6,
            SORTEROPTO_TO = 7,
            TOOCLOSECOIN = 8,
            ACCEPTGATENOTREADY = 9,
            CREDITSENSORNOTREADY = 10,
            SORTERNOTREADY = 11,
            REJECTCOINNOTCLEARED = 12,
            VALIDATORSENSORNOTREADY = 13,
            CREDITSENSORBLOCKED = 14,
            SORTEROPTOBLOCKED = 15,
            CREDITSEQERROR = 16,
            COINGOINGBACK = 17,
            COINTOOFAST = 18,
            COINTOOSLOW = 19,
            COSMECHACTIVED = 20,
            DCEOPTO_TO = 21,
            DCEOPTONOTSEE = 22,
            CREDITSENSORREACHEDEARLY = 23,
            TOOREJECTEDCOIN = 24,
            REJECTSLUG = 25,
            REJECTSENSORBLOCKED = 26,
            GAMESOVERLOAD = 27,
            MAXCOINMETERPULSESEXCEEDED = 28,
            ACCEPTGATEOPENNOTCLOSED = 29,
            ACCEPTGATECLOSEDNOTOPEN = 30,
            MANIFOLDTIMEOUT = 31,
            MANIFOLDOPTOBLOCKED = 32,
            MANIFOLDNOTREADY = 33,
            SECURITYSTATUSCHANGED = 34,
            MOTOEXCEPTION = 35,
            SWALLOWEDCOIN = 36,
            COIN2FAST = 37,
            COIN2SLOW = 38,
            COININCORRECTLYSORTED = 39,
            EXTERNALLIGHTATTACK = 40,
            INHIBITEDCOIN_1 = 128,
            INHIBITEDCOIN_2 = 129,
            INHIBITEDCOIN_3 = 130,
            INHIBITEDCOIN_4 = 131,
            INHIBITEDCOIN_5 = 132,
            INHIBITEDCOIN_6 = 133,
            INHIBITEDCOIN_7 = 134,
            INHIBITEDCOIN_8 = 135,
            INHIBITEDCOIN_9 = 136,
            INHIBITEDCOIN_10 = 137,
            INHIBITEDCOIN_11 = 138,
            INHIBITEDCOIN_12 = 139,
            INHIBITEDCOIN_13 = 140,
            INHIBITEDCOIN_14 = 141,
            INHIBITEDCOIN_15 = 142,
            INHIBITEDCOIN_16 = 143,
            INHIBITEDCOIN_17 = 144,
            INHIBITEDCOIN_18 = 145,
            INHIBITEDCOIN_19 = 146,
            INHIBITEDCOIN_20 = 147,
            INHIBITEDCOIN_21 = 148,
            INHIBITEDCOIN_22 = 149,
            INHIBITEDCOIN_23 = 150,
            INHIBITEDCOIN_24 = 151,
            INHIBITEDCOIN_25 = 152,
            INHIBITEDCOIN_26 = 153,
            INHIBITEDCOIN_27 = 154,
            INHIBITEDCOIN_28 = 155,
            INHIBITEDCOIN_29 = 156,
            INHIBITEDCOIN_30 = 157,
            INHIBITEDCOIN_31 = 158,
            INHIBITEDCOIN_32 = 159,
            DATABLOCKREQUESTED = 253,
            COINRETURNMECHACTIVATED = 254,
            UNSPECIFIEDALARM = 255,
        }
    }
}