//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceLibrary {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class messagesText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messagesText() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviceLibrary.messagesText", typeof(messagesText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activation du {0}.
        /// </summary>
        public static string activationCV {
            get {
                return ResourceManager.GetString("activationCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le build code du {0} est &quot;{1}&quot;.
        /// </summary>
        public static string buildCode {
            get {
                return ResourceManager.GetString("buildCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bus ccTalk trouvé sur le port COM{0}..
        /// </summary>
        public static string busOKfinded {
            get {
                return ResourceManager.GetString("busOKfinded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appel de la dll.
        /// </summary>
        public static string callDll {
            get {
                return ResourceManager.GetString("callDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Instanciation ccTalk..
        /// </summary>
        public static string ccTalkInstance {
            get {
                return ResourceManager.GetString("ccTalkInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commande {0} moteur du pelicano .
        /// </summary>
        public static string cmdMotorPelicano {
            get {
                return ResourceManager.GetString("cmdMotorPelicano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le moteur du pelicano est activé..
        /// </summary>
        public static string cmdMotorPelicanoInProgress {
            get {
                return ResourceManager.GetString("cmdMotorPelicanoInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activation du moteur du pelicano commande {0}.
        /// </summary>
        public static string cmdMotorPelicanoMode {
            get {
                return ResourceManager.GetString("cmdMotorPelicanoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effectue un self test du {0}.
        /// </summary>
        public static string cmdSelfTest {
            get {
                return ResourceManager.GetString("cmdSelfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La version de la data base du {0} est &quot;{1}&quot;.
        /// </summary>
        public static string dataBaseVersion {
            get {
                return ResourceManager.GetString("dataBaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Desactivation du {0}.
        /// </summary>
        public static string deactivationCV {
            get {
                return ResourceManager.GetString("deactivationCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delai maximum entre 2 commande pour le {0} est de {1} ms.
        /// </summary>
        public static string delayPolling {
            get {
                return ResourceManager.GetString("delayPolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echo : .
        /// </summary>
        public static string echo {
            get {
                return ResourceManager.GetString("echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;identitification de l&apos;equipement est &quot;{0}&quot;.
        /// </summary>
        public static string equipementID {
            get {
                return ResourceManager.GetString("equipementID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ERREUR {0} {1} {2}..
        /// </summary>
        public static string erreur {
            get {
                return ResourceManager.GetString("erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;effectuer la commande {0} sur le {1}.
        /// </summary>
        public static string erreurCmd {
            get {
                return ResourceManager.GetString("erreurCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de lire la délai du polling {0}.
        /// </summary>
        public static string erreurPollingPriority {
            get {
                return ResourceManager.GetString("erreurPollingPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de conversion du numero de port {0}..
        /// </summary>
        public static string erreurPort {
            get {
                return ResourceManager.GetString("erreurPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de lire le masque d&apos;inhibition des canaux du {0}.
        /// </summary>
        public static string errGetInhibitStatus {
            get {
                return ResourceManager.GetString("errGetInhibitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de modifier l&apos;habitation des canaux du {0}.
        /// </summary>
        public static string errInhibitStatus {
            get {
                return ResourceManager.GetString("errInhibitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;enregistrer le master inhibit status du {0}.
        /// </summary>
        public static string errMasterInhibitStatus {
            get {
                return ResourceManager.GetString("errMasterInhibitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;executer la commande sur le moteur du pelicano.
        /// </summary>
        public static string errMotorPelicano {
            get {
                return ResourceManager.GetString("errMotorPelicano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande du code de fabrication du {0}.
        /// </summary>
        public static string getBuildCode {
            get {
                return ResourceManager.GetString("getBuildCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture de l&apos;octet dans  le {0}.
        /// </summary>
        public static string getByte {
            get {
                return ResourceManager.GetString("GetByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande de la version de la data base du {0}.
        /// </summary>
        public static string getDataBaseVersion {
            get {
                return ResourceManager.GetString("getDataBaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le périphérique est un {0}.
        /// </summary>
        public static string getEquipementID {
            get {
                return ResourceManager.GetString("getEquipementID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du masque d&apos;inhibitiion des canaux du {0}.
        /// </summary>
        public static string getInhibitStatus {
            get {
                return ResourceManager.GetString("getInhibitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande de l&apos;identifiant du fabricant du {0}.
        /// </summary>
        public static string getManufacturer {
            get {
                return ResourceManager.GetString("getManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture de l&apos;inhibition du {0}.
        /// </summary>
        public static string getMasterInhibt {
            get {
                return ResourceManager.GetString("getMasterInhibt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande du délai de polling pour le {0}.
        /// </summary>
        public static string getPolling {
            get {
                return ResourceManager.GetString("getPolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande du code produit du  {0}.
        /// </summary>
        public static string getProductCode {
            get {
                return ResourceManager.GetString("getProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande du numéro de série du {0}.
        /// </summary>
        public static string getSN {
            get {
                return ResourceManager.GetString("getSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande de la vérivision software du {0}.
        /// </summary>
        public static string getSWRev {
            get {
                return ResourceManager.GetString("getSWRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture de la chaine ASCII dans le {0}.
        /// </summary>
        public static string getText {
            get {
                return ResourceManager.GetString("getText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HELLO.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifie l&apos;habilitation  des canaux du {0} {1} {2}.
        /// </summary>
        public static string inhibitStatus {
            get {
                return ResourceManager.GetString("inhibitMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à le {0} est {1}.
        /// </summary>
        public static string inhibitStatusResult {
            get {
                return ResourceManager.GetString("inhibitStatusResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;identifiant du fabricant du {0} est &quot;{1}&quot;.
        /// </summary>
        public static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Lecture impossible, pas de bus ccTalk ou pas de periphérique ccTalk reconnu ou periphérique HS sur le port {1}..
        /// </summary>
        public static string noccTalkDevice {
            get {
                return ResourceManager.GetString("noccTalkDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture du délai de polling.
        /// </summary>
        public static string polling {
            get {
                return ResourceManager.GetString("polling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le code produit du {0} est &quot;{1}&quot;.
        /// </summary>
        public static string productCode {
            get {
                return ResourceManager.GetString("productCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture de la réponse du périphérique..
        /// </summary>
        public static string readAnswerDevice {
            get {
                return ResourceManager.GetString("readAnswerDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture de l&apos;écho..
        /// </summary>
        public static string readEcho {
            get {
                return ResourceManager.GetString("readEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche du port série ccTalk..
        /// </summary>
        public static string search_ccTalk {
            get {
                return ResourceManager.GetString("search_ccTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le résultat du self test du {0} est {1}.
        /// </summary>
        public static string selfTest {
            get {
                return ResourceManager.GetString("selfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi de la commande &quot;{0}&quot; au {1}..
        /// </summary>
        public static string sendCmd {
            get {
                return ResourceManager.GetString("sendCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoie la commande master inhibit {0} au {1}.
        /// </summary>
        public static string sendMasterInhibitStatus {
            get {
                return ResourceManager.GetString("sendMasterInhibitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le numéro de série du {0} est {1}.
        /// </summary>
        public static string serialNumber {
            get {
                return ResourceManager.GetString("serialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à *************************************************.
        /// </summary>
        public static string starLine {
            get {
                return ResourceManager.GetString("starLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La revision software du {0} est {1}.
        /// </summary>
        public static string swRev {
            get {
                return ResourceManager.GetString("swRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test moteur {0}.
        /// </summary>
        public static string testMotor {
            get {
                return ResourceManager.GetString("testMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test des bobines du {0}.
        /// </summary>
        public static string testSolenoid {
            get {
                return ResourceManager.GetString("testSolenoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réponse : .
        /// </summary>
        public static string txtAnswer {
            get {
                return ResourceManager.GetString("txtAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message envoyé : .
        /// </summary>
        public static string txtMessageSended {
            get {
                return ResourceManager.GetString("txtMessageSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vérification sur le port série {0}..
        /// </summary>
        public static string verifSerialPort {
            get {
                return ResourceManager.GetString("verifSerialPort", resourceCulture);
            }
        }
    }
}
